### ISSUE TITLE
Cannot create directory "//.cache": Permission denied

### ISSUE THREAD

**Issue by rPetas** [wslutilities/wslu#101]
**Background Information:**
 - Build: 17763
 - WSL: Ubuntu 18.04.03
- Version: wslu/bionic-updates,now 2.3.2-0ubuntu2~18.04.3 all [installed]

**Describe the bug**
While starting mysql server using the command "sudo service mysql start", starts mysql successfully but reports the following error:

mkdir: cannot create directory ‘//.cache’: Permission denied
-su: 19: /etc/profile.d/wsl-integration.sh: cannot create //.cache/wslu/integration: Directory nonexistent

**Comment by crramirez** [comment]
Hello,

This is because mysql creates an user and login without the WSL interop. The WSL-integration needs to check for the Path if windows executables are accessible.

Regards

**Comment by patrick330602** [comment]
Thank you for the feedback. Unfortunately, the Ubuntu version of WSL Utilities is maintained by the Ubuntu team, and it is suggested to submit the bug to <https://bugs.launchpad.net/wslu> instead.

Also cc @rbalint

**Comment by rPetas** [comment]
> 
> 
> Hello,
> 
> This is because mysql creates an user and login without the WSL interop. The WSL-integration needs to check for the Path if windows executables are accessible.
> 
> Regards

This means i am missing some variable in my environment?

**Comment by rPetas** [comment]
@crramirez This means I am missing some variable in my environment?

@patrick330602 sorry if i barked at the wrong tree. I am new in the community and wasn't sure where i should report my issue. I only thought it could be affecting more people since its pretty recent and this was the first place i found. Should I open it there now?

**Comment by crramirez** [comment]
Hello @rPetas 

Your environment is right. The problem is with the script "/etc/profile.d/wsl-integration.sh". As a quick workaround insert the following line before the first line in "/etc/profile.d/wsl-integration.sh" (use sudo to edit the file):

```
# Check if we have HOME folder
if [[ "${HOME}" == "/" ]]; then
  exit 0
fi
```

I mean before the line: 
WSL_INTEGRATION_CACHE=$HOME/.cache/wslu/integration

And yes open the issue there. Opening it here won't get the issue fixed.

Regards

**Comment by rbalint** [comment]
Thanks, I've opened a bug for it at Ubuntu: https://bugs.launchpad.net/ubuntu/+source/wslu/+bug/1859509

@crramirez `exit 0` is not a great idea in script which are sourced.

**Comment by DaltonHarvey** [comment]
**Hi guys I hade the same error:**
`-su: 19: /etc/profile.d/wsl-integration.sh: cannot create //.cache/wslu/integration: Directory nonexistent`

trying to run mysql-server:5.7 on wsl ubunu 18.4

My solution was to install using **docker** 

```
docker pull mysql/mysql-server:5.7
```

````
docker run --name mysql-connection-docker -e MYSQL_ROOT_PASSWORD=<password> -p 3306:3306 -d mysql/mysql-server:5.7 --character-set-server=utf8m
b4 --collation-server=utf8mb4_unicode_ci
````

**Comment by ewein** [comment]
I'm having the same issues.

**Comment by epassossilva** [comment]
> 
> 
> Hello @rPetas
> 
> Your environment is right. The problem is with the script "/etc/profile.d/wsl-integration.sh". As a quick workaround insert the following line before the first line in "/etc/profile.d/wsl-integration.sh" (use sudo to edit the file):
> 
> ```shell
> # Check if we have HOME folder
> if [[ "${HOME}" == "/" ]]; then
>   exit 0
> fi
> ```
> 
> I mean before the line:
> 
> ```shell
> WSL_INTEGRATION_CACHE=$HOME/.cache/wslu/integration`
> ```
> 
> And yes open the issue there. Opening it here won't get the issue fixed.
> 
> Regards

This worked for me, thanks.

**Comment by ewein** [comment]
Doing the above didn't work: I now returns:

```
No directory, logging in with HOME=/
-su: 2: /etc/profile.d/wsl-integration.sh: [[: not found
mkdir: cannot create directory ‘//.cache’: Permission denied
-su: 24: /etc/profile.d/wsl-integration.sh: cannot create //.cache/wslu/integration: Directory nonexistent
```

**Comment by crramirez** [comment]
Hello

Here an improved version. Insert the following line before the first line in "/etc/profile.d/wsl-integration.sh" (use sudo to edit the file):

```bash
# Check if we have HOME folder
if [ "${HOME}" = "/" ]; then
  return
fi
```

I mean before the line: 
```bash
WSL_INTEGRATION_CACHE=$HOME/.cache/wslu/integration`
```

Regards

**Comment by ewein** [comment]
That removed the error thanks @crramirez.

**Comment by djrobby** [comment]
Thanks @crramirez, I can also confirm that your **improved version** worked!

**Comment by crramirez** [comment]
@wrapper but no error message? Can you verify if MySQL in fact was successfully started?

**Comment by patrick330602** [comment]
> I just tried this (improved version) and I get:
> 
> ```
> 
>  No directory, logging in with HOME=/
>                                                                                                                                       [fail]
> ```

@wrapper which version of wslu are you using? you can check by `wslfetch --version`

**Comment by wrapper** [comment]
@crramirez It just said [fail] and mysql wasn't running

@patrick330602 wslu v2.3.2; wslfetch v44

I purged mysql and installed mariadb-server php-mysql and this seems to be working

**Comment by patrick330602** [comment]
@wrapper Thank you. wslu 2.3.2 is the old version that does not come with the fix. The fix is available for Ubuntu 20.04 but it is not yet backported. The process of backporting the latest version with the fix to Ubuntu 18.04 and Ubuntu 16.04 will take weeks.

**Comment by FloWulli** [comment]
I got the same problem after some updates and changes. But no suggestions from here helped.
Then I retried by deleting the existing .cache folder as root and after reloading WSL, the error disappeard.
Maybe this will also work for some of you guys.

**Comment by nicolasducere** [comment]
@FloWulli you removed the cache folder from which directory ?

**Comment by FloWulli** [comment]
In my home directory. Afterwards everything worked fine again

**Comment by ankitddn** [comment]
> @crramirez It just said [fail] and mysql wasn't running
> 
> @patrick330602 wslu v2.3.2; wslfetch v44
> 
> I purged mysql and installed mariadb-server php-mysql and this seems to be working

how does purging mysql solve this purpose for you?

**Comment by armavion** [comment]
> Hello
> 
> Here an improved version. Insert the following line before the first line in "/etc/profile.d/wsl-integration.sh" (use sudo to edit the file):
> 
> ```shell
> # Check if we have HOME folder
> if [ "${HOME}" = "/" ]; then
>   return
> fi
> ```
> 
> I mean before the line:
> 
> ```shell
> WSL_INTEGRATION_CACHE=$HOME/.cache/wslu/integration`
> ```
> 
> Regards

KEEP IN MIND that you need a full windows restart in order for this code to work.
Thanks @crramirez !

**Comment by crramirez** [comment]
@armavion You are welcome.

`wsl.exe --terminate Ubuntu` should be enough. You can see the exact name executing:

`wsl.exe --list`

**Comment by rakesh001** [comment]
> Hello @rPetas
> 
> Your environment is right. The problem is with the script "/etc/profile.d/wsl-integration.sh". As a quick workaround insert the following line before the first line in "/etc/profile.d/wsl-integration.sh" (use sudo to edit the file):
> 
> ```shell
> # Check if we have HOME folder
> if [[ "${HOME}" == "/" ]]; then
>   exit 0
> fi
> ```
> 
> I mean before the line:
> 
> ```shell
> WSL_INTEGRATION_CACHE=$HOME/.cache/wslu/integration`
> ```
> 
> And yes open the issue there. Opening it here won't get the issue fixed.
> 
> Regards

This works for me magically.
Thank you.

**Comment by ultrageek** [comment]
Just FYI, none of these solutions worked for me... Until I

**Comment by hundanLi** [comment]
I change it like this:
```bash
     # create empty cache
     # Check if we have HOME folder
     if [[ "${HOME}" != "/" ]]; then
          [ -d $HOME/.cache/wslu ] || mkdir -p $HOME/.cache/wslu
          echo -n "" > $WSL_INTEGRATION_CACHE
     fi
```
works well for me.

**Comment by Nilard** [comment]
> I just tried this (improved version) and I get:
> 
> ```
> 
>  No directory, logging in with HOME=/
>                                                                                                                                       [fail]
> ```

@wrapper  To fix this you need to run the following  (under root or sudo):
```
service mysql stop
usermod -d /var/lib/mysql/ mysql
service mysql start
```

**Comment by saurabhmaun** [comment]
> terwards everything worked fine agai



> I got the same problem after some updates and changes. Unfortunatly no suggestions from here helped.
> Then deleted the existing .cache folder as root and after reloading WSL, the error disappeard.
> Maybe this will also work for some of you guys.

This worked for me like charm... Thanks

**Comment by tianc43** [comment]
> > I just tried this (improved version) and I get:
> > ```
> > 
> >  No directory, logging in with HOME=/
> >                                                                                                                                       [fail]
> > ```
> 
> @wrapper To fix this you need to run the following (under root or sudo):
> 
> ```
> service mysql stop
> usermod -d /var/lib/mysql/ mysql
> service mysql start
> ```

Great！！！
