### ISSUE TITLE
baseexec_gen for non-Store distros

### ISSUE THREAD

**Issue by jclds139** [wslutilities/wslu#104]
**Background Information:**
 - Build: 19041.21 (should be unrelated)
 - WSL: Arch
 - Version: current

**Describe the bug**
The new "baseexec_gen" function, which has to succeed at least once,

**To Reproduce**
- Install a non-store Distro (using [wsldl](https://github.com/yuk7/wsldl), or `wsl --import`
- Install wslu >= 2.3.3 in that Distro
- Run any wslu command (`wslvar`, `wslview`, `wslupath`, `wslsys`, `wslfetch`, `wslusc`, and `wslsys` are all affected)
  - See error messages appear related to a registry key and some path executables listed by `find`
  - From what I can tell, the commands then proceed to function correctly despite this function failing.

**Expected behavior**
- wslu commands to function as normal, without error messages

**Additional context**
The current `baseexec_gen` in the header expects a registry key called "PackageFamilyName" to be present for the current Distro, which doesn't seem to be created for Distros installed manually instead of through the store.

Also, within that function, the first call to `reg.exe` doesn't fully qualify the path which may cause issues if these commands are run during login before `$PATH` is fully set up.

**Comment by patrick330602** [comment]
Thank you for the feedback. Sorry for not considering this scenario, will fix it as soon as possible.
