### ISSUE TITLE
Extra 'fi' at line 124 of wslu_header

### ISSUE THREAD

**Issue by PGScully** [wslutilities/wslu#107]
**Background Information:**
 - Build: Win 10 Pro 1909
 - WSL: Pengwin
 - Version: 2.3.5-2

**Describe the bug**
Attempting to run any wslu command results in an error.  e.g.:
$ wslvar JAVA_HOME
/usr/bin/wslvar: line 125: syntax error near unexpected token `else'
/usr/bin/wslvar: line 125: `    else'

**To Reproduce**
Run any wslu command

**Expected behavior**
The command will run normally.

**Additional context**
There's 2x if and 3x fi in wslu_header (https://github.com/wslutilities/wslu/blob/master/src/wslu-header#L124), and the resulting imbalance is causing errors.  Someone has already created pull request https://github.com/wslutilities/wslu/pull/106 to fix it.

**Comment by patrick330602** [comment]
Merged and will manually submit the package to fix this problem. Sorry for the problem caused.
