### ISSUE TITLE
wslupath manpage out-of-date

### ISSUE THREAD

**Issue by niklasholm** [wslutilities/wslu#108]
**Background Information:**
 - Build: 1909 18363.657
 - WSL: Ubuntu 18.04
 - Version: 2.3.2

**Describe the bug**
The manpage for `wslupath` contains out-of-date information. Specifically, it wasn't updated with commit fb8a4099.

**To Reproduce**
`man wslupath`

**Expected behavior**
Deprecated or not, one should expect a correct manpage.

**Comment by patrick330602** [comment]
Thank you for reporting. I will update the manpage for `wslupath` in the 2.x version and 3.x version. Unfortunately, the Ubuntu version of the package is maintained by the Ubuntu Desktop team. I will update the package but the Ubuntu version will take a longer time to arrive in `main`.
