### ISSUE TITLE
WSLFetch never shows correctly

### ISSUE THREAD

**Issue by giggio** [wslutilities/wslu#111]
**Background Information:**
 - Build: `Microsoft Windows [Version 10.0.18363.752]`
 - WSL: Happens on Ubuntu (19.10) and openSUSE Leap (42.3).
 - Version: `wslu v3.0.0-1; wslfetch v44` (openSuse) `wslu v2.3.2; wslfetch v44` (Ubuntu)

**Describe the bug**

When you run `wslfetch` it displays incorrectly, the system info ends up way to the right, and ends up creating a new line, disrupting the logo.

This is what happens when you first run it (started from `bash --noprofile --norc`:

![image](https://user-images.githubusercontent.com/334958/79084190-d382da80-7d08-11ea-8d62-ef1ff9e769ed.png)

Then, if you resize the window, it shows correctly:

![image](https://user-images.githubusercontent.com/334958/79084204-e09fc980-7d08-11ea-83d7-3cbcd4b40cc4.png)

But if then you run it again, it again calculates the columns incorrectly, and overlaps:

![image](https://user-images.githubusercontent.com/334958/79084250-13e25880-7d09-11ea-9a19-e56b233f8b63.png)

So this shows that it is not a problem of the window being too small (not enough columns), but wslfetch is calculating the width it needs incorrectly.

**To Reproduce**
Run wsl and then wslfetch.

**Expected behavior**
wslfetch understands the number of columns and shows up correctly.

**Comment by patrick330602** [comment]
Interesting. I do not have the width calculation for the rows. I only have the calculation for the boundary line, which is not enabled by default. My local testing on Fedora, OpenSUSE, Pengwin and Ubuntu on both old Windows Console and Windows Terminal also have no such problem. What font are you using?

**Comment by patrick330602** [comment]
Need more people to confirm this behavior

**Comment by giggio** [comment]
I'm using DejaVu Sans Mono for Powerline. Just tried with Consolas, got the same results.

**Comment by giggio** [comment]
The problem does not happen in the Window Terminal. Only if I run Ubuntu/openSuse directly. Confirmed for Ubuntu and Suse.

**Comment by giggio** [comment]
The problem also does not happen when running cmd and then bash, or powershell and then bash (or ubuntu or openSUSE-42.exe).

**Comment by patrick330602** [comment]
Interesting. Still cannot reproduce. Could you show your bash.exe property window?

**Comment by giggio** [comment]
Sure.

![options](https://user-images.githubusercontent.com/334958/79238716-1e563c80-7e46-11ea-95e2-291b480ea72d.png)

![font](https://user-images.githubusercontent.com/334958/79238642-01ba0480-7e46-11ea-9845-522fef077653.png)

![layout](https://user-images.githubusercontent.com/334958/79238668-0c749980-7e46-11ea-8570-4e29c222e909.png)

![colors](https://user-images.githubusercontent.com/334958/79238679-10a0b700-7e46-11ea-884f-3c2ebfeada57.png)

![terminal](https://user-images.githubusercontent.com/334958/79238690-14ccd480-7e46-11ea-8b1d-1a94feac448a.png)

![terminal](https://user-images.githubusercontent.com/334958/79238863-4645a000-7e46-11ea-8dd4-e029a76c66e9.png)

**Comment by patrick330602** [comment]
Really interesting, the settings are identical. More tests show that still works under zsh/fish. could you use `wslfetch | cat -A` and show the screenshot of it? Thanks!

**Comment by giggio** [comment]
Sure. This is what I get:

````
❯ wslfetch | cat -A
$
^[[31m                          ./+o+-      ^[(B^[[m^[[31m^[[1mWindows 10 Linux Subsystem^[(B^[[m$
^[(B^[[m                  yyyyy. ^[[31m'yyyyyy+     ^[(B^[[m^[[31m^[[1mgiggio^[(B^[[m@^[[31m^[[1mgiggiosurfacepro5^[(B^[[m$
^[(B^[[m              .;//+/////h ^[[31myyyyyyo     ^[(B^[[m^[[31m^[[1mBUILD:^[(B^[[m^I18363$
^[[1;33m           .++ ^[(B^[[m.:/++++++/-^[[31m.`sss/`     ^[(B^[[m^[[31m^[[1mBRANCH:^[(B^[[m^I19h1_release$
^[[1;33m         .:++o: ^[(B^[[m`\++++++++/:---:/-    ^[(B^[[m^[[31m^[[1mRELEASE:^[(B^[[m^IUbuntu 19.10$
^[[1;33m        o:+o+:++. ^[(B^[[m`````'-/ooo+++++\   ^[(B^[[m^[[31m^[[1mKERNEL:^[(B^[[m^ILinux 4.4.0-18362-Microsoft$
^[[1;33m       .:+o:+o/.          ^[(B^[[m`+sssooo+\  ^[(B^[[m^[[31m^[[1mUPTIME:^[(B^[[m^I0d 0h 15m$
^[(B^[[m  .++/+ ^[[1;33m+oo+o:`             ^[(B^[[m\sssooo;  ^[(B^[[m$
^[(B^[[m /+++//+: ^[[1;33moo+o                        ^[(B^[[m   ^[[40m   ^[[41m   ^[[42m   ^[[43m   ^[[44m   ^[[45m   ^[[46m   ^[[47m   ^[(B^[[m$
^[(B^[[m \+/+o+++ ^[[1;33mo++o               ^[[31mydddhh+  ^[(B^[[m$
^[(B^[[m  .++.o+ ^[[1;33m+oo+:`             ^[[31m/dddhhh;  ^[(B^[[m$
^[[1;33m       .+.o+oo:.           ^[[31moddhhhh+   ^[(B^[[m$
^[[1;33m        \+.++o+o` ^[[31m-,,,,.:ohdhhhhh+    ^[(B^[[m$
^[[1;33m         `:o+++  ^[[31mohhhhhhhhyo++os:     ^[(B^[[m$
^[[1;33m           .o: ^[[31m.syhhhhhhh'^[[1;33m.oo++o.     ^[(B^[[m$
^[[31m               /osyyyyyyy^[[1;33m.oooo+++\    ^[(B^[[m$
^[[31m                   ````` ^[[1;33m+oo+++o:/    ^[(B^[[m$
^[[1;33m                          `oo++'`     ^[(B^[[m$
$
````

![image](https://user-images.githubusercontent.com/334958/79647341-96926a00-8186-11ea-90c2-503d59de2f01.png)

**Comment by giggio** [comment]
From looking at the output, it seems the tab output is going all the way to the right.
I can confirm the behavior. This is Ubuntu directly:
![image](https://user-images.githubusercontent.com/334958/79650291-7020fe80-8187-11ea-858b-967735ce12fa.png)
This is it on the Windows Terminal:
![image](https://user-images.githubusercontent.com/334958/79650595-84fd9200-8187-11ea-8e26-c2c8559ead13.png)

So this does not seem a problem in wslfetch, but I have no idea what would be causing this... I just ran `bash.exe --noprofile --norc` and the problem also shows, so it is not something from my profile files, but from WSL itself.

**Comment by giggio** [comment]
Ok, I added `tabs -4` to my `.bashrc`, and it is fixed. Weird!

![image](https://user-images.githubusercontent.com/334958/79653783-74015080-8188-11ea-9d6e-7b3f2d1b2f7d.png)

Learned it at SuperUser: https://superuser.com/questions/1503681/wsl-tab-character-takes-up-an-entire-line

Thanks for the help!

**Comment by patrick330602** [comment]
Glad you solve the problem! This is very interesting to see
