### ISSUE TITLE
wslact time-sync throws "date: invalid date"

### ISSUE THREAD

**Issue by ricardosantos9521** [wslutilities/wslu#113]
**Background Information:**
 - Build: 19041.173
 - WSL: Ubuntu 18.04
 - Version: 3.0

**Describe the bug**
This probably happens when linux and windows languages are different
- Windows is in pt-pt when i run "Get-Date -UFormat "%d %b %Y %T %Z" date "14 abr 2020 13:38:09 +01" is returned (month is in portuguese). Ubuntu is in english and will not accept month 'abr'.

**To Reproduce**
```script
ricardo@surface: sudo wslact ts
[info] Before Sync: 14 Apr 2020 00:12:28 WEST
date: invalid date '14 abr 2020 13:45:57 +01'
[error] Time Sync failed.
```
**Expected behavior**
wslact time-sync should set Windows date in Ubuntu.

**Additional context**
- I try the command in powershell "Get-Date -UFormat "%d %m %Y %T %Z" to display month with numbers ("14 04 2020 13:45:57 +01") but date -s doesn't accept the format either.
- There is also a problem with the +01 for some reason date -s doesn't accept that (returns "date: extra operand ‘+01’")  but accept +01:00.

**Comment by patrick330602** [comment]
Thank you for the bug report and pull request! I will take a look, and close once the fix is released.
