### ISSUE TITLE
Can't install wslu on Alpine

### ISSUE THREAD

**Issue by giggio** [wslutilities/wslu#116]
**Background Information:**
 - Build: Version 10.0.19041.207
 - WSL: Alpine Linux v3.11.3

**Describe the bug**
I can't install it, as per the readme file, with the commands:
```sh
echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing/" | sudo tee -a /etc/apk/repositories
sudo apk update
sudo apk add wslu@testing
```

I get an error:

````
# apk add wslu@testing
ERROR: unsatisfiable constraints:
  wslu (missing):
    required by: world[wslu]
````

**To Reproduce**
Install Alpine Linux from the store, run it, type `su`, enter password, install sudo (`apk update; apk add sudo`), run the above commands.

**Expected behavior**
wslu is installed.

**Comment by patrick330602** [comment]
oops, sorry for that. wslu recently is moved from testing to community, so use this instead: `echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/community/" | sudo tee -a /etc/apk/repositories`.

I will change the information on the README now

**Comment by giggio** [comment]
It worked, thanks.

**Comment by dominik-ba** [comment]
Here it still has the old reference: https://wslutiliti.es/wslu/install.html
