### ISSUE TITLE
wslfetch errors on Alpine due to wrong `grep` used

### ISSUE THREAD

**Issue by giggio** [wslutilities/wslu#117]
**Background Information:**
 - Build: `10.0.19041.207`
 - WSL: `Alpine Linux 3.11.3`
 - Version: `wslu v3.0.1-1; wslfetch v44`

**Describe the bug**
It seems that an error in a call to grep fails.

This is the error screen:
![error on alpine](https://user-images.githubusercontent.com/334958/80555065-86a83080-89a5-11ea-993c-35fd8906780a.png)

The error message is:
`grep: unrecognized option: P`

I tried it on bash and on ash.

**To Reproduce**
Install Alpine Linux from the store, install wslu, run wslfetch.

**Expected behavior**
It shows the usual fetch screen.

**Comment by patrick330602** [comment]
Thank you for the bug report. This is mainly due to the `grep` come with the Alpine is the wrong one. For now, you can solve the issue by installing another `grep` from `apk` using `apk add grep`. I will update the dep in 3.1.

**Comment by giggio** [comment]
Yes, this works! Thanks!
