### ISSUE TITLE
Add support for Clear Linux

### ISSUE THREAD

**Issue by WSLUser** [wslutilities/wslu#124]
**Background Information:**
 - Build: [e.g. 17704]  Any build that supports `wsl --import`.
 - WSL: [e.g. Ubuntu 16.04] Clear Linux (imported)
 - Version: [e.g. 1.5] N/A

**Describe the bug**
I'm unable to use wslu on Clear Linux after importing.
**To Reproduce**
Use this guide to get Clear Linux: https://community.clearlinux.org/t/tutorial-clearlinux-on-wsl2/1835. If you use the provided tar.gz it will take several swupd updates.
**A clear and concise description of what you expected to happen.**
swupd bundle-add wslu
**Additional context**

**Comment by WSLUser** [comment]
https://docs.01.org/clearlinux/latest/guides/clear/swupd-3rd-party.html#related-topics will probably help with this. You can re-use existing fedora rpm following this guide (you can ignore the server setup as you're already hosting it on a server, you'll just need to add a ClearLinux option there.)

**Comment by WSLUser** [comment]
Any updates on getting the repository up?

**Comment by patrick330602** [comment]
I am recently way too busy with my work so I haven't focus a lot on this project, I wil try to set one up tomorrow

**Comment by patrick330602** [comment]
You can now install it on Clear Linux: https://blog.wslutiliti.es/2022/08/08/wslu-now-available-on-clearlinux/

**Comment by WSLUser** [comment]
Thanks! I really appreciate it. Now we can see about making it officially available in their repo.
