### ISSUE TITLE
Deps: Update bat-core

### ISSUE THREAD

**Issue by WSLUser** [wslutilities/wslu#125]
**Background Information:**
 - Build: [e.g. 17704] N/A
 - WSL: [e.g. Ubuntu 16.04] N/A
 - Version: [e.g. 1.5] N/A

**Describe the bug**
https://github.com/bats-core/bats-core is at 1.2 released in April, however in the `extras` project folder, the commit is from 2017.
**To Reproduce**
Just go to https://github.com/bats-core/bats-core/releases
**Expected behavior**
I'd like to see updated bash tests for supporting newer systems.
**Additional context**
This is just general good practice. I recommend making it a git submodule to more easily update it.

**Comment by patrick330602** [comment]
Thanks for the heads up. I just realized this today after I was requested by someone for test coverage and right now I am updating locally. This will be fixed for development branch (aka 4.x)
