### ISSUE TITLE
wslusc shortcut not working

### ISSUE THREAD

**Issue by alexynior28** [wslutilities/wslu#129]
I am creating the following, however when I double-click, the screen opens and closes.

wslusc -n sc script.sh

The path of the direct link is as follows:

C:\Users\User\AppData\Local\Microsoft\WindowsApps\KaliLinux.54290C8133FEE_ey8k8hqnwqnmg\kali.exe run " bash -l -c script.sh"

**Comment by patrick330602** [comment]
Thanks for the reply. It seems that it is not properly reading the absolute path of your script. I will try to investigate this issue.

**Comment by alexynior28** [comment]
Thank you

**Comment by patrick330602** [comment]
[HW] Encountered some issues when handling the space in paths. Will insvestigate the issue and release the fix until this is getting fixed.
