### ISSUE TITLE
Add IPv4 details in wslfetch

### ISSUE THREAD

**Issue by reconified** [wslutilities/wslu#139]
Hi Team, IPv4 details on wslfetch would be really great. It would easier for user's like me who RDP into machine quite occasionally.

**Comment by patrick330602** [comment]
Thanks for the feature suggestion! I will put it on the roadmap.

**Comment by ThatWeirdAndrew** [comment]
I'm on it. Which branch should i commit to?

**Comment by ThatWeirdAndrew** [comment]
Also, @reconified is there any other information besides the IPv4 address that you would like displayed?

**Comment by reconified** [comment]
That would be all.
