### ISSUE TITLE
[Enhancement] Use autospec for rpm generation

### ISSUE THREAD

**Issue by WSLUser** [wslutilities/wslu#140]
**Background Information:**
 - Build: [e.g. 17704]
 - WSL: [e.g. Ubuntu 16.04]
 - Version: [e.g. 1.5]
N/A
**Describe the bug**
N/A
**To Reproduce**
N/A
**Expected behavior**
More efficient way of generating rpms that should allow more rpm based distros to be supported such as Clear Linux while also consolidating rpm builds to a single build process
**Additional context**
Should help resolve https://github.com/wslutilities/wslu/issues/124  Also, you can pull it in via https://github.com/clearlinux/autospec as a git submodule so you can update it easily.

**Comment by patrick330602** [comment]
Thanks. I will try to check it out

**Comment by patrick330602** [comment]
I will start to work on this in the following days

**Comment by patrick330602** [comment]
This is now completed and got initial builds. Since the file it generated is way too different from the current ones, they will be differently hosted. the official repository will be up in the following days. Closing this one and once the repository is completed, #124 will be also closed.

**Comment by patrick330602** [comment]
After further testing, autospec is relatively a lot slower than current build solutions, will end up not using autospec

**Comment by WSLUser** [comment]
I think you still need it for Clear Linux though

**Comment by patrick330602** [comment]
For Clear Linux, generating 3rd party packages do not need to use `autospec` since it do not use rpms. That is only used for submitting **packages**. Since I am building a **bundle**, which requires to use just **source packages contents**, `autospec` become useless as we just need to use the `mixer` bundle.

**Comment by WSLUser** [comment]
Oh cool. I didn't realize that.
