### ISSUE TITLE
Spaces in user path still broken

### ISSUE THREAD

**Issue by plttn** [wslutilities/wslu#144]
**Background Information:**
 - Build: 19041
 - WSL: Pengwin

**Describe the bug**
Spaces in user path still cause issues with `wslfetch` and `wslsys`

**To Reproduce**
- have space in user path (C:\Users\Jack Platten\..\..)
- run `wslfetch` or `wslsys`
- observe "the term 'C:\\Users\\Jack' is not recognized as the name of a cmdlet...

**Expected behavior**

**Comment by loadhigh** [comment]
In wslsys:

    function call_display_scaling() {
        up_path="$(wslvar -s USERPROFILE)"
        wslu_file_check "$(wslpath "$up_path")/wslu" "get_dpi.ps1" "?!S"
        display_scaling="$(winps_exec "$(double_dash_p "$up_path" | sed -e 's| |\` |')\\wslu\\get_dpi.ps1" | sed -e 's|\r||g')"
        bc -l <<< "$(printf "%d\n" "$display_scaling")/100" | sed -e "s/\.0//g" -e "s/0*$//g"
    }

Fixed by adding ``sed -e 's| |\` |'``
