### ISSUE TITLE
wslusc with "bash: - : invalid option" warning

### ISSUE THREAD

**Issue by smallst** [wslutilities/wslu#147]
**Background Information:**
 - Build: [ 19041.450 // is this mean the windows version?]
 - WSL: [ Archlinux ]
 - Version: [ 3.2.0 ]

**Describe the bug**
i use wslusc to create a emacs shortcut with gui in wsl2. the shortcut command (Arch is my wsl2 name) is 
```
C:\Windows\System32\wscript.exe C:\\Users\\xxx\wslu\runHidden.vbs C:\\Windows\\System32\\wsl.exe -d Arch -e  /usr/share/wslu/wslusc-helper.sh "/usr/sbin/emacs "
```

and the emacs start with an warning (which i can see in *scratch* page) with:
```lisp
;; bash: - : invalid option
;; Usage:	bash [GNU long option] [option] ...
;; 	bash [GNU long option] [option] script-file ...
;; GNU long options:
;; 	--debug
;; 	--debugger
;; 	--dump-po-strings
;; 	--dump-strings
;; 	--help
;; 	--init-file
;; 	--login
;; 	--noediting
;; 	--noprofile
;; 	--norc
;; 	--posix
;; 	--pretty-print
;; 	--rcfile
;; 	--restricted
;; 	--verbose
;; 	--version
;; Shell options:
;; 	-ilrsD or -c command or -O shopt_option		(invocation only)
;; 	-abefhkmnptuvxBCHP or -o option
```

run the shortcut comman in powershell has the same warning but if i run the command `/usr/share/wslu/wslusc-helper.sh "/usr/sbin/emacs "` directly in wsl2, no warning appears.

**To Reproduce**

i think use the emacs config files from https://github.com/redguardtoo/emacs.d can reproduce this bug.
**Expected behavior**

i want no warnings. because my *scratch* page will shows some interesting words instead.

**Additional context**

**Comment by smallst** [comment]
looked into the helper shell scripts, i think the problem may come from CR and LF ?

**Comment by patrick330602** [comment]
Which version of wslu are you using and are you using the AUR version of wslu?

**Comment by smallst** [comment]
@patrick330602 oh, yes, i use the AUR version of wslu
 `wslusc -v` shows `wslu v3.2.0-1; wslusc v40`

**Comment by patrick330602** [comment]
I am unable to reproduce such bug, even using the configuration you provided:
![image](https://user-images.githubusercontent.com/15316889/92447765-44f88380-f1ea-11ea-818f-25bdfb411e3d.png)
More detail is possibly needed

**Comment by smallst** [comment]
thanks! i'll try to find more details

**Comment by smallst** [comment]
not sure adding a default 'bash' here is a good way for wslusc to avoid similiar issues. anyway, my problem is solved. wslu is a great job!  👍
