### ISSUE TITLE
Png icon doesn't work

### ISSUE THREAD

**Issue by romanlex** [wslutilities/wslu#150]
**Background Information:**
 - Build: 2004
 - WSL: 20.04
 - Version: 3.2.1

**Describe the bug**
I'm trying generate windows shortcut with linux gui app with `-i {path}.png`
But png not work
![image](https://user-images.githubusercontent.com/3369304/93067319-c2594380-f683-11ea-8c81-eb5ce6bfeb9b.png)

**To Reproduce**
`wslusc -g /usr/bin/gitkraken -i /usr/share/gitkraken/gitkraken.png`

**Expected behavior**
Windows shortcut with icon

**Comment by patrick330602** [comment]
Hi @romanlex,

You are using the command wrong. What you input means **creating a GUI shortcut with the command `/usr/bin/gitkraken -i /usr/share/gitkraken/gitkraken.png`**. 

Correct command should be `wslusc -i /usr/share/gitkraken/gitkraken.png -g /usr/bin/gitkraken`. 

This is also stated in the `wslusc --help` that command should always be at last:
```
wslusc - Part of wslu, a collection of utilities for Windows 10 Windows Subsystem for Linux
Usage: wslusc [-gi] [-e PATH] [-n NAME] [-i FILE] COMMAND
wslusc [-hv]
```

**Comment by crramirez** [comment]
I recommend to use the interactive mode for that: 

`wslusc -I`
