### ISSUE TITLE
Arch Linux (AUR) no longer hosts wslu

### ISSUE THREAD

**Issue by tranzystorek-io** [wslutilities/wslu#152]
Due to a AUR rules violation (regarding package intent for non-Arch distros), the packages there were deleted.

Here are the related posts:
https://lists.archlinux.org/pipermail/aur-requests/2020-September/044992.html
https://lists.archlinux.org/pipermail/aur-requests/2020-September/044993.html

At the very least, the README should be updated, but maybe a custom hosting could be created, as per the second link?

**Comment by patrick330602** [comment]
Thanks, I am aware of it. I am a little busy and I will get a build later today

**Comment by patrick330602** [comment]
Updated README to reflect the change.

**Comment by Hkyx** [comment]
Didn't found any aur package available, do you got a link may be ?
