### ISSUE TITLE
A new clone is missing the bats dependency which is required to run tests

### ISSUE THREAD

**Issue by royvou** [wslutilities/wslu#153]
**Background Information:**
Current ```dev/master``` branch is unable to run any tests out of the box.
Branch is in the current state:  https://github.com/wslutilities/wslu/tree/20c1f18fbead0118015ef3db7b1b9d242f87c0c8

**Describe the bug**

After cloning the solution (with the steps mentioned in CONTRIBUTING.md (Great start btw!) i wanted to try and see if i could pick some of the issues up with the current hacktober fest. But i noticed i was unable to run any test.

**To Reproduce**

- Follow the contributing.md
```bash
git clone --recursive --branch dev/master https://github.com/wslutilities/wslu.git
./configure.sh
make
sudo make res_install
```
- make test

**Expected behaviour**
Test start running and all complete successfully after a clean clone.

**Additional context**
The commit "https://github.com/wslutilities/wslu/commit/d5fd2b171034ee072652fe91be9f6631459f8169" removed the bats submodule.

**Comment by patrick330602** [comment]
Thank you for the report. I noticed that you have opened a PR for that; however, it is not a good practice to do so since different distribution will offer a different version of bats. I have updated the submodule so right now it works properly. Sorry for the hassles caused.
