### ISSUE TITLE
Error with Trailing Slash in wslview

### ISSUE THREAD

**Issue by AlJohri** [wslutilities/wslu#165]
**Background Information:**
 - Build: 19041
 - WSL: Ubuntu 20.04 LTS
 - Version: 3.2.1-1

**Describe the bug**
`wslview` doesn't work with trailing slash at the end of folder

**To Reproduce**
```
mkdir testfolder
wslview testfolder
wslview testfolder/
```

**Expected behavior**
I expect the folder to open in explorer.

**Additional context**
It seems to work fine using [wsl-open](https://github.com/4U6U57/wsl-open)
![Screen Shot 2021-01-03 at 2 51 02 AM](https://user-images.githubusercontent.com/2790092/103474155-01182400-4d6f-11eb-94a6-2314f6651de9.png)

**Comment by patrick330602** [comment]
Thanks for reporting, I will look into this.

**Comment by patrick330602** [comment]
Thanks for reporting, the bug is found. I am currently fixing it.
