### ISSUE TITLE
Does not work with Browser Chooser 2

### ISSUE THREAD

**Issue by McDemigod** [wslutilities/wslu#167]
**Background Information:**
 - Build: https://github.com/wslutilities/wslu/commit/d8fb31bab12b66deb06428fb58353493087a558b
 - WSL: tested in Pengwin & Ubuntu 20.04
 - Version: 

**Describe the bug**
Nothing appears when Windows has  [Browser Chooser 2](https://bitbucket.org/gmyx/browserchooser2/wiki/Home) set as default browser

**To Reproduce**
Set default in Windows settings.

**Expected behavior**
Should open Browser Chooser window with options to select other browsers installed in Windows.

**Comment by patrick330602** [comment]
Hi,

Thanks for the report. I will check it this weekend.

**Comment by patrick330602** [comment]
Hi, 

After some testing, this related to the upstream issue here: 
https://bitbucket.org/gmyx/browserchooser2/issues/47/cant-open-a-link-on-slack

Someone also made a fork to address this issue:
https://bitbucket.org/Verbail/browserchooser2rrfork/downloads/
I have tested locally and this release works with `wslview`.

**Comment by patrick330602** [comment]
Due to some upstream issue, I am pausing the fix for this: https://github.com/microsoft/WSL/issues/6565

**Comment by patrick330602** [comment]
After several more tests and inactivity on the Microsoft side, with limited resources, I won't fix this bug.

**Comment by patrick330602** [comment]
Thinking about solving this issue by providing alternative engine.
