### ISSUE TITLE
wslsys reports wrong WSL Version on Debian buster

### ISSUE THREAD

**Issue by jegHEEK73** [wslutilities/wslu#168]
**Background Information:**
 - Build: [19042]
 - WSL: [Debian GNU/Linux 10 (buster)]
 - Version: [10.0.19042]

**Describe the bug**
Command returns the incorrect version of WSL

**Steps To Reproduce**
$ wslsys
WSL Version: 1
Locale: en_US
Release Install Date: Thu Jan 14 15:54:04 MST 2021
Branch: vb_release
Build: 19042
Full Build: 19041.1.amd64fre.vb_release.191206-1406
Display Scaling: 1.5
Windows Theme: light
Windows Uptime: 12d 20h 50m
WSL Uptime: 3d 6h 1m
WSL Release: Debian GNU/Linux 10 (buster)
WSL Kernel: Linux 5.4.72-microsoft-standard-WSL2
Packages Count: 1002

**Expected behavior**
WSL Version: 2

**Additional context**

Return status appears OK after command runs:
echo $?
0

adding `--debug --verbose` outputs one extra line at start:
[debug] Showing debug output.
WSL Version: 1
...

**Comment by patrick330602** [comment]
Hi, 
what version of wslu are you using? you can check via `wslsys -v`

**Comment by jegHEEK73** [comment]
```
$ wslsys -v
wslu v3.1.1-1; wslsys v34

**Comment by patrick330602** [comment]
This is possibly my fault... I will take a book at the repository

**Comment by patrick330602** [comment]
Hi, I just updated the Debian package that fixes the issue, can you check whether it is fixed? Thanks!

**Comment by jegHEEK73** [comment]
Looks good! After updating wslu 

`wslu/unknown 3.2.2-1 all [upgradable from: 3.1.1-1]`

I see from `man wslu` 

AVAILABLE COMMANDS
       wslusc, wslsys, wslfetch, wslvar, wslview(wview/wslstart/wstart), wslupath(deprecated), wslact

**Comment by patrick330602** [comment]
> Looks good! After updating wslu
> 
> `wslu/unknown 3.2.2-1 all [upgradable from: 3.1.1-1]`
> 
> I see from `man wslu`
> 
> AVAILABLE COMMANDS
> wslusc, wslsys, wslfetch, wslvar, wslview(wview/wslstart/wstart), wslupath(deprecated), wslact

Is it still reporting the wrong WSL version?

**Comment by jegHEEK73** [comment]
$ wslsys -v
wslu v3.2.2-1; wslsys v34

**Comment by patrick330602** [comment]
> $ wslsys -v
> wslu v3.2.2-1; wslsys v34

Uh I mean, is the `wslsys` still reporting WSL version 1?

**Comment by jegHEEK73** [comment]
No, that's fixed!
```$ wslsys
WSL Version: 2
Locale: en_US
Release Install Date: Thu Jan 14 15:54:04 MST 2021
Branch: vb_release
Build: 19042
Full Build: 19041.1.amd64fre.vb_release.191206-1406
Display Scaling: 1.5
Windows Theme: light
Windows Uptime: 6d 2h 17m
WSL Uptime: 6d 1h 22m
WSL Release: Debian GNU/Linux 10 (buster)
WSL Kernel: Linux 5.4.72-microsoft-standard-WSL2
Packages Count: 1016```

**Comment by patrick330602** [comment]
Thanks for confirming! I will close this now.
