### ISSUE TITLE
Suggestion for man page

### ISSUE THREAD

**Issue by jegHEEK73** [wslutilities/wslu#169]
These are so handy, but I soon forget some of them. Could the man page list them all?

THANKS

**Comment by patrick330602** [comment]
Hi,

Can you elaborate a bit more? I am not sure what your question means

**Comment by jegHEEK73** [comment]
Somewhere on the man page output it would be nice to have a list of all the commands that are part of wslu. Just now I tried letting bash attempt to discover the commands:
```
$ wsl <TAB><TAB>
wslact wslfetch wslpath wslstart wslsys wslupath wslusc wslvar wslview
```
Are all these part of wslu? I think so, but the man page for wslu _could_ list all the supported commands. In fact the list incorporated in the man page _could_ be generated from the makefile when everything is built.

**Comment by patrick330602** [comment]
Everything except `wslpath` (This is a tool by Microsoft) belongs to wslu. I will consider including the details in the manpages.
