### ISSUE TITLE
Issue with wslfetch in debian

### ISSUE THREAD

**Issue by justsomeon123** [wslutilities/wslu#173]
**Background Information:**
 - Build: [19041]
 - WSL: [Debian 10]

**Bug**
Using wslfetch in debian while your microsoft account name has a space in it raises error:

C:\\Users\\user: The term 'C:\\Users\\user' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
 C:\\Users\\user lastname\wslu\get_dpi.ps1

     CategoryInfo          : ObjectNotFound: (C:\\Users\\user:String) [], CommandNotFoundException
     FullyQualifiedErrorId : CommandNotFoundException

My idea of what is happening here is that someone forgot to put quotes around the variable containing the path so that any user with a space in their name will not successfully run the command. Also after the error it prints the design.   

**To Reproduce**
Get wsl 2 with debian, Get WSLU, run wslfetch.

**Expected behavior**
Prints info and picture closes out with no error

**Comment by patrick330602** [comment]
Hi, I just updated the Debian package that fixes the issue, can you check whether it is fixed? Thanks!

**Comment by patrick330602** [comment]
Hi, 

Can you check whether it is fixed? Thanks!

**Comment by patrick330602** [comment]
Close due to confirmed in other similar reports and issue inactivity.
