### ISSUE TITLE
Use correct Icon for Windows shortcuts instead of generic one

### ISSUE THREAD

**Issue by Novaal** [wslutilities/wslu#176]
**Background Information:**
 - WSL: Ubuntu 20.04
 - Version: wslu v3.2.1-1; wslusc v40

**Description**
Use correct Icon for Windows shortcuts instead of generic one.

**To Reproduce**

Create a Windows Shortcut for any graphical linux program, e.g:
```bash
wslusc -g evolution
```

**Expected behavior**

- Finds correct icon like [here](https://askubuntu.com/a/52432) 
- converts found image to ico with e.g.:

```bash
sudo apt install imagemagick
convert -background transparent /usr/share/icons/Yaru/256x256@2x/apps/evolution.png -define icon:auto-resize=16,24,32,48,64,72,96,128,256 /mnt/c/Users/USERNAME_HERE/wslu/evolution.ico
```

- sets the converted ico as Icon for the shortcut

**Additional context**
- https://askubuntu.com/a/52432
- https://stackoverflow.com/a/49823738
- https://askubuntu.com/a/867568

**Comment by patrick330602** [comment]
Thanks for the suggestion. I will take a look.
