### ISSUE TITLE
Missing wslu package from version 3.2.2 assets

### ISSUE THREAD

**Issue by tranzystorek-io** [wslutilities/wslu#177]
As in the title, there is no `.zst` file in the 3.2.2 release assets, I'm not sure how to install it on Arch Linux

**Comment by patrick330602** [comment]
Hi, 

All releases are gradually rolling out, being released doesn't mean they are immediately available for every distro. Packages for Arch Linux, Kali Linux, Ubuntu, and Alpine Linux all needed to be manually packaged. Hope you understand.
