### ISSUE TITLE
wslview: opens powershell windows when opening file in GUI application launched from the Start Menu

### ISSUE THREAD

**Issue by diddledani** [wslutilities/wslu#181]
**Background Information:**
 - Build: 21343
 - WSL: Ubuntu on WSL Community Preview
 - Version: v3.2.1-1

**Describe the bug**
When running a GUI application from the Windows Start Menu that tries to open a wslview-supported file in Windows there are multiple powershell windows that open. These should ideally be eliminated or hidden.

**To Reproduce**

1. Install Windows Insider build 21332 or later
2. Install Ubuntu on WSL Community Preview
3. Install nautilus: `sudo apt install -yqq nautilus`
4. Open nautilus by selecting "Files" from the Windows Start Menu
5. Navigate to a PDF file in nautilus and double-click to open it

**Expected behavior**
Silently launch the file in the correct Windows application, without popping up any intermediary powershell windows.

**Comment by patrick330602** [comment]
This should be fixed in 4.0.0
