### ISSUE TITLE
ERROR: UtilConnectToInteropServer:300

### ISSUE THREAD

**Issue by AbstProcDo** [wslutilities/wslu#184]
**Background Information:**
 - Build: 19042
 - WSL: Ubuntu 20.04
 - wslu v2.3.6; wslview v06

**Describe the bug**
It report the following error when try to open apps from WSL2-VcxSrv-Emacs
<3>init: (3701) ERROR: UtilConnectToInteropServer:300: connect failed 2

**Expected behavior**
Open windows-apps from a linux-gui-terminal

**Additional context**
Strike M-& to call async-shell to open apps with `wslview .` , then it report error:
`<3>init: (4803) ERROR: UtilConnectToInteropServer:300: connect failed 2`

**Comment by patrick330602** [comment]
Thanks for reporting, but what is WSL2-VcXsrv-Emacs?

**Comment by AbstProcDo** [comment]
Thank you, VcXsrv Windows  is X Server to run Llinux Graphical application from wsl2 in Emacs. WSL2-VcXsrv-Emacs is run a linux graphical Emacs in Windows from wsl2.

**Comment by patrick330602** [comment]
> Thank you, VcXsrv Windows is X Server to run Llinux Graphical application from wsl2 in Emacs. WSL2-VcXsrv-Emacs is run a linux graphical Emacs in Windows from wsl2.

Can you link to the project? I am unable to find it

**Comment by AbstProcDo** [comment]
"VcXsrv Windows X Server " https://sourceforge.net/projects/vcxsrv/
