### ISSUE TITLE
Fedora COPR repo doesn't include builds for Fedora 34

### ISSUE THREAD

**Issue by hybridAries** [wslutilities/wslu#188]
I tried installing WSLU via the instructions provided for Fedora via the [README](https://github.com/wslutilities/wslu#fedora), but it fails, likely because there is no build for Fedora 34 in the COPR repo. Command and message:

```
% sudo dnf copr enable wslutilities/wslu
[sudo] password for XXXXX:
Enabling a Copr repository. Please note that this repository is not part
of the main distribution, and quality may vary.
...
Do you really want to enable copr.fedorainfracloud.org/wslutilities/wslu? [y/N]: Y
Error: This repository does not have any builds yet so you cannot enable it now.
```

**Comment by patrick330602** [comment]
Hi,

My COPR account got hacked and I am locked out from my own account. Currently, I am contacting them to solve the issue. Sorry for the inconvenience caused.

**Comment by crramirez** [comment]
Hello.

Meanwhile you can use https://copr.fedorainfracloud.org/coprs/trustywolf/wslu/ it doesn't include the lastest version of wslu but will work with Fedora 34

Regards

**Comment by da-moo** [comment]
> 
> 
> Hi,
> 
> My COPR account got hacked and I am locked out from my own account. Currently, I am contacting them to solve the issue. Sorry for the inconvenience caused.

I'd be lying if I said I wasn't concerned that the project's COPR account was compromised in a way that could allow malicious code to be installed on end-user machines. Do you have any further information besides that the account was "hacked"?

**Comment by patrick330602** [comment]
> > Hi,
> > My COPR account got hacked and I am locked out from my own account. Currently, I am contacting them to solve the issue. Sorry for the inconvenience caused.
> 
> I'd be lying if I said I wasn't concerned that the project's COPR account was compromised in a way that could allow malicious code to be installed on end-user machines. Do you have any further information besides that the account was "hacked"?

The current versions are safe, checking from the code. The build information can be public viewed: https://copr.fedorainfracloud.org/coprs/wslutilities/wslu/builds/ ; However, I do not guarantee it will be always safe. For people who currently using wslu, it should be safe, since files are all batch files and source code can be easily inspected.

**Comment by patrick330602** [comment]
As the account is recovered, wslu 3.2.3 for Fedora 34 is now available. Sorry for the long wait.
