### ISSUE TITLE
Seems not support open windows volume under /mnt， like /mnt/e

### ISSUE THREAD

**Issue by roachsinai** [wslutilities/wslu#198]
**Background Information:**
 - Build: [19043]
 - WSL: [ArchWSL]
 - Version: [3.2.3]

**Describe the bug**

Can't open explorer.exe under /mnt/e by `wslview .`.

**To Reproduce**

Open a wsl tab, `cd /mnt/e` or other windoes volume, then run `wslview .` get below error:

![image](https://user-images.githubusercontent.com/9500049/125442377-3b584a5b-eb06-41d9-8341-66e7c4997681.png)

Above text just flashed past, I captured it by transcribe a small viedo.

**Expected behavior**

`explorer .` works well under `/mnt/e`, expect `wslview .` has same behavior.

Thanks in advance!

**Comment by patrick330602** [comment]
It looks like an encoding problem. Can you post a result from Windows PowerShell with the command `Get-Culture | Format-List -Property *`?

**Comment by roachsinai** [comment]
```
Parent                         : zh-CHS
LCID                           : 2052
KeyboardLayoutId               : 2052
Name                           : zh-CN
IetfLanguageTag                : zh-CN
DisplayName                    : 中文(简体，中国)
NativeName                     : 中文(中国)
EnglishName                    : Chinese (Simplified, China)
TwoLetterISOLanguageName       : zh
ThreeLetterISOLanguageName     : zho
ThreeLetterWindowsLanguageName : CHS
CompareInfo                    : CompareInfo - zh-CN
TextInfo                       : TextInfo - zh-CN
IsNeutralCulture               : False
CultureTypes                   : SpecificCultures, InstalledWin32Cultures, FrameworkCultures
NumberFormat                   : System.Globalization.NumberFormatInfo
DateTimeFormat                 : System.Globalization.DateTimeFormatInfo
Calendar                       : System.Globalization.GregorianCalendar
OptionalCalendars              : {System.Globalization.GregorianCalendar}
UseUserOverride                : True
IsReadOnly                     : False
```

**Comment by roachsinai** [comment]
Hi, @patrick330602 is the info above enough to help you to locate bug? Or what extra infos should I provide?

**Comment by patrick330602** [comment]
Sorry, this is still being investigated.

**Comment by roachsinai** [comment]
> Sorry, this is still being investigated.

Thanks for your reply :)

**Comment by Zebartin** [comment]
I am going on similar issue with almost the same background.

`wslview /mnt/` works just fine, and then when I mannually open `e/` in Windows Explorer, it fails saying I have no access to the network resource.
![image](https://user-images.githubusercontent.com/16185081/128969626-ca1ea285-c0f1-4da8-b47e-be456e93e71c.png)

Seems like a deliberate setting of wsl, not sure.

**Comment by patrick330602** [comment]
> I am going on similar issue with almost the same background.
> 
> `wslview /mnt/` works just fine, and then when I mannually open `e/` in Windows Explorer, it fails saying I have no access to the network resource.
> ![image](https://user-images.githubusercontent.com/16185081/128969626-ca1ea285-c0f1-4da8-b47e-be456e93e71c.png)
> 
> Seems like a deliberate setting of wsl, not sure.

Interesting.... I will take a further look

**Comment by A-23187** [comment]
Possibly related to https://github.com/microsoft/WSL/issues/3853.  So `powershell.exe -Command Start \\wsl$\<distro>\mnt\<drive>` doesn't work. The path needs to be converted to Windows style, e.g. `/mnt/e` to `E:\` manually or using `$(wslpath /mnt/e)`.
