### ISSUE TITLE
Terminal logs are cleared on cmd.exe

### ISSUE THREAD

**Issue by kmyk** [wslutilities/wslu#199]
**Background Information:**

1.  - Build: 18363
    - WSL: Ubuntu 20.04.2 LTS
    - Version: wslu v2.3.2; wslview v06
2.
    - Build: 18363
    - WSL: Debian GNU/Linux 10 (buster)
    - Version: wslu v3.2.3-1; wslview v10

**Describe the bug**
When we use `cmd.exe` as a terminal emulator, terminal logs are cleared in running wslu commands.

**To Reproduce**

1. Open `cmd.exe`
2. Start a WSL session with `$ wsl.exe`
3. Run `$ wslsys` in the WSL

**Expected behavior**
Terminal logs (e.g. a prompt and command `$ wslsys`) should be kept, but they are cleared.

**Additional context**
- This issue happens on all commands (e.g. `wslview`, `wslsys`, `wslfetch`, ...)
- This issue doesn't happen on other terminal emulators ([Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701) and [wsltty](https://github.com/mintty/wsltty))
- I encountered this issue with `wslview` inside of Python's standard [webbrowser](https://docs.python.org/ja/3/library/webbrowser.html) module

**Comment by patrick330602** [comment]
Can you use the following command `Get-Culture | Format-List -Property *` in Windows PowerShell and post the result here?

**Comment by kmyk** [comment]
This is the result of the command (executed on `cmd.exe`)

```
C:\Users\kimiyuki>powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

新しいクロスプラットフォームの PowerShell をお試しください https://aka.ms/pscore6

PS C:\Users\kimiyuki> Get-Culture | Format-List -Property *


Parent                         : ja
LCID                           : 1041
KeyboardLayoutId               : 1041
Name                           : ja-JP
IetfLanguageTag                : ja-JP
DisplayName                    : 日本語 (日本)
NativeName                     : 日本語 (日本)
EnglishName                    : Japanese (Japan)
TwoLetterISOLanguageName       : ja
ThreeLetterISOLanguageName     : jpn
ThreeLetterWindowsLanguageName : JPN
CompareInfo                    : CompareInfo - ja-JP
TextInfo                       : TextInfo - ja-JP
IsNeutralCulture               : False
CultureTypes                   : SpecificCultures, InstalledWin32Cultures, FrameworkCultures
NumberFormat                   : System.Globalization.NumberFormatInfo
DateTimeFormat                 : System.Globalization.DateTimeFormatInfo
Calendar                       : System.Globalization.GregorianCalendar
OptionalCalendars              : {System.Globalization.GregorianCalendar, System.Globalization.JapaneseCalendar, System
                                 .Globalization.GregorianCalendar}
UseUserOverride                : True
IsReadOnly                     : False
```

**Comment by waynejhou** [comment]
I think the clear effect is case by function `winps_exec` in source file `wslu-header`
which try to change codepage to windows default codepage (in my case is 950 for traditional chinese) to exec powershell and change back to 65001.
you can edit the file in `~/.config/wslu/oemcp` which has codepage of your windows
change the value to 65001 to cheese  codepage changing

**Comment by kmyk** [comment]
I tried `$ echo 65001 > ~/.config/wslu/oemcp` and this suppressed the clear effect.
