### ISSUE TITLE
Scripts break if /etc/wsl.conf has 'root'

### ISSUE THREAD

**Issue by IsaacOscar** [wslutilities/wslu#200]
The following line here is problematic: https://github.com/wslutilities/wslu/blob/bc889504af415b3ee0e5885a0304a8de68c1ab78/src/wslu-header#L115

It causes all the wsl utilities to break when `/etc/wsl.conf` has the word `root` in places other than the name of a property:

For example:
```
[automount]
root = /

[user]
default = root
```

Causes the interop_prefix to be set `/\nroot` which is clearly invalid.

Here is a simple fix (I don't know `awk` so there's probably a better one):
```
grep '^\s*root\s*=' /etc/wsl.conf | awk -F '=' '/root/ {print $2}' | awk '{$1=$1;print}'
```

**Comment by diddledani** [comment]
Maybe a more robust ini parser can help, e.g. https://github.com/albfan/bash-ini-parser

**Comment by patrick330602** [comment]
Thank you for this information. I will fix this as soon as possible.
