### ISSUE TITLE
wslview does not open with `xdg-open`

### ISSUE THREAD

**Issue by giggio** [wslutilities/wslu#210]
**Background Information:**
 - Build: Version 10.0.22000.318 (Windows 11, 21H2)
 - WSL: Ubuntu 20.04.3 LTS
 - Version: wslu v2.3.6; wslview v06

**Describe the bug**
If you run `xdg-open http://github.com` it will open with the default browser for GUI, if it exists.
This only happens with WSLg, which is part of Windows 11. This problem started happening to me when I upgraded to Windows 11.

**To Reproduce**
Setup WSL2 with Windows 11 and run `xdg-open http://github.com`.

**Expected behavior**
Site open in default Windows browser, not in browser form WSLg.

**Additional context**
`wslview` is correctly registered and used to work on Windows 10 with `xdg-open`.

`xdg-open` is a script and is checking for a display. See this function in it:

```bash
has_display()
{
    if [ -n "$DISPLAY" ] || [ -n "$WAYLAND_DISPLAY" ]; then
        return 0
    else
        return 1
    fi
}
```

Both of these variables have values. Later, when it will open for the link, it checks if this returns 1, and does not use `x-www-browser` or `www-browser` or `$BROWSER`.

**Comment by giggio** [comment]
I found a workaround, you can see it in this commit in dofiles: https://github.com/giggio/dotfiles/commit/005679180ba89df76c5e9d7d9cfebd7071eef30a

You need to create a `.desktop` file and set your default mimes for xdg.

**Comment by patrick330602** [comment]
Can you swtich the package to this? https://launchpad.net/~wslutilities/+archive/ubuntu/wslu

This one is the latest, due to that fact that currently I left Canonical and the current package in PPA is still not properly handled by the team for nearly a year.
