### ISSUE TITLE
wslview: provide wslview.desktop to simplify making it default browser for xdg-open

### ISSUE THREAD

**Issue by wojciechka** [wslutilities/wslu#214]
**Background Information:**
 - Build: Windows 11 10.0.22000.348
 - WSL: 20.04
 - Version: 2.3.6-0ubuntu2~20.04.0

**Describe the bug**
Currently there is no way to make `wslview` the default browser for tools that use `xdg-open` to open the browser.

I am using `kubectl` with `oidc-login`, which uses OAuth 2 for logging in to Kubernetes clusters. This uses `xdg-open` which does not use the `x-www-browser` default as well as ignores the `BROWSER` variable. I am using 2FA hardware key so I need to log in from the Windows browser that has access to the token.

`xdg-open` requires a `.desktop` file that specifies how to run items and it would be convenient for `wslu` packages to also ship the file. 

I manually created `/usr/share/applications/wslview.desktop` and set it with `xdg-settings` like this:

```bash
#!/bin/bash

set -eu -o pipefail

sudo sh -c 'cat >/usr/share/applications/wslview.desktop' <<EOF
[Desktop Entry]
Version=1.0
Name=WSLview
Exec=wslview %u
Terminal=false
X-MultipleArgs=false
Type=Application
Categories=GNOME;GTK;Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;video/webm;application/x-xpinstall;
EOF

xdg-settings set default-web-browser wslview.desktop
```

I was able to solve it, but I did not find documentation and had to learn a bit about XDG to get to this. It would be great if `wslu` package shipped the `wslview.desktop` file and then changing the browser would just be a matter of `xdg-settings set default-web-browser wslview.desktop`, so it's easier for people to switch to the host browser.

**To Reproduce**

Install `xdg-utils` package on Ubuntu inside WSL and run `xdg-open https://github.com`.

**Expected behavior**
Windows browser opened by default, or at least make it easier to switch the default browser.

**Additional context**
Tested on Ubuntu 20.04, but I am sure this applies to more Linux distributions.

**Comment by patrick330602** [comment]
Can you swtich the package to this? https://launchpad.net/~wslutilities/+archive/ubuntu/wslu

This one is the latest, due to that fact that currently I left Canonical and the current version (3.x) in PPA is still not properly handled and SRUed by the team for nearly a year.
