### ISSUE TITLE
Duplcate code  in wslview can be eliminated

### ISSUE THREAD

**Issue by jayrajput** [wslutilities/wslu#216]
Code from L51-L56 in wslview is same as code from L59-L64 and can be eliminated by using else condition in place of elseif. I can do the clean, if it is OK. I will need some hand holding though in terms of running the test and making sure I do not break anything. I use WSL2 and so my interest is using the script to open window files.

https://github.com/wslutilities/wslu/blob/master/src/wslview.sh#L51

**Comment by patrick330602** [comment]
The Code has been already reduced in lts/master branch. I am right now doing the final test to get it packaged.
