### ISSUE TITLE
[wslusc] Shortcut is invalid after I change the icon of it.

### ISSUE THREAD

**Issue by stskyblade** [wslutilities/wslu#217]
**Background Information:**
 - wslu v2.3.6; wslusc v37
 - WSL: Ubuntu 20.04

**Describe the bug**
I use this command `wslusc -g -e "export DISPLAY=$(grep -m 1 nameserver /etc/resolv.conf | awk '{print $2}'):0 LIBGL_ALWAYS_INDIRECT=1;" $(which emacs)` to create a shortcut for emacs. 
That shortcut works. But after I changed the icon of it, it doesn't work anymore. (spacemacs.ico downloaded from here: https://github.com/nashamri/spacemacs-logo)

**Comment by patrick330602** [comment]
Can you show the results from the Windows PowerShell using `$s=(New-Object -COM WScript.Shell).CreateShortcut("<PATH/TO/YOUR/SHORCUT>"); $s` and replace `<PATH/TO/YOUR/SHORCUT>` with the path to your shortcut? Thank you!

**Comment by patrick330602** [comment]
Also, please try out the PPA version of wslu using the method here: https://wslutiliti.es/wslu/install.html#ubuntu

**Comment by stskyblade** [comment]
```
PS C:\Users\stskyblade> $s=(New-Object -COM WScript.Shell).CreateShortcut("C:\\Users\\stskyblade\\Desktop\\emacs.lnk"); $s


FullName         : C:\Users\stskyblade\Desktop\emacs.lnk
Arguments        : C:\\Users\\stskyblade\wslu\runHidden.vbs "C:\\Users\\stskyblade\\AppData\\Local\\Microsoft\\WindowsApps\\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\\ubuntu2004.exe" run "cd ~;
                    . /usr/share/wslu/wsl-integration.sh; export DISPLAY=172.21.0.1:0 LIBGL_ALWAYS_INDIRECT=1; /usr/bin/emacs"
Description      :
Hotkey           :
IconLocation     : C:\\Users\\stskyblade\wslu\wsl.ico,0
RelativePath     :
TargetPath       : C:\Windows\System32\wscript.exe
WindowStyle      : 1
WorkingDirectory :

```

**Comment by patrick330602** [comment]
Are you using Windows 11 with WSLg?

**Comment by stskyblade** [comment]
I'm using Windows 10.

**Comment by patrick330602** [comment]
Can you print the content of the shortcut after you change the icon? Thanks!

**Comment by stskyblade** [comment]
Do you mean the output of `$s=(New-Object -COM WScript.Shell).CreateShortcut("C:\\Users\\stskyblade\\Desktop\\emacs-27.127.lnk"); $s` ?

This is a shortcut with original icon, and it doesn't work now.

```
PS C:\Users\stskyblade>  $s=(New-Object -COM WScript.Shell).CreateShortcut("C:\\Users\\stskyblade\\Desktop\\emacs-27.127.lnk"); $s


FullName         : C:\Users\stskyblade\Desktop\emacs-27.127.lnk
Arguments        : C:\\Users\\stskyblade\wslu\runHidden.vbs C:\\Users\\stskyblade\\AppData\\Local\\Microsoft\\WindowsApps\\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\\ubuntu2004.exe run export D
                   ISPLAY=172.21.128.1:0 LIBGL_ALWAYS_INDIRECT=1; /usr/share/wslu/wslusc-helper.sh "/usr/bin/emacs-27.127 "
Description      :
Hotkey           :
IconLocation     : C:\\Users\\stskyblade\wslu\wsl-gui.ico,0
RelativePath     :
TargetPath       : C:\Windows\System32\wscript.exe
WindowStyle      : 1
WorkingDirectory :
```

**Comment by stskyblade** [comment]
I have confirmed there is a network adapter which has IP `172.21.128.1` in the Task Manager of Win10.

**Comment by patrick330602** [comment]
Interesting... I am really unable to reproduce your bug. I will try to look for some other people who can help.
