### ISSUE TITLE
Suggestion: a clipboard manager

### ISSUE THREAD

**Issue by lenormf** [wslutilities/wslu#221]
Hi,

It’d be nice to have a utility that allows interacting with the host clipboard in a UNIX-y manner: read on stdin via pipe, via redirection etc.

Thanks!

**Comment by patrick330602** [comment]
Have you tried using `clip.exe` on WSL? Technically saying this should just work and do not need any wrapper

**Comment by lenormf** [comment]
Yes, one example of why a wrapper that follows UNIX conventions would be that `echo text | clip.exe` doesn’t work.

**Comment by kforeverisback** [comment]
I use a bash function `clip` which converts the line-ending to Windows and copies to the clipboard.

```bash
clip () {
        local clip_path=/mnt/c/Windows/System32/Clip.exe
        local in=$1
        [ ! -f ${clip_path} ] && echo "${clip_path} binary not found" && return 1
        [ -z "$in" ] && in=`cat`
        echo ${in} | sed 's#\n$#\r\n#g' | ${clip_path}
}
```

**Comment by patrick330602** [comment]
> I use a bash function `clip` which converts the line-ending to Windows and copies to the clipboard.
> 
> ```shell
> clip () {
>         local clip_path=/mnt/c/Windows/System32/Clip.exe
>         local in=$1
>         [ ! -f ${clip_path} ] && echo "${clip_path} binary not found" && return 1
>         [ -z "$in" ] && in=`cat`
>         echo ${in} | sed 's#\n$#\r\n#g' | ${clip_path}
> }
> ```

The script you provided hangs for me interestingly
<img width="920" alt="スクリーンショット 2022-03-29 午前8 57 12" src="https://user-images.githubusercontent.com/15316889/160511254-502cb2f6-cdbf-4f22-a6c9-70103132231e.png">
