### ISSUE TITLE
Utility for forwarding WSL IPs to local windows IPs

### ISSUE THREAD

**Issue by kiikoh** [wslutilities/wslu#229]
There are a few times this would be useful, primarily for accessing websites and apps in development on a mobile device to test compatibility. 

The WSLHostPatcher listed here does not work for me so it may act as a good jumping off point, but cannot be sure
https://blog.expo.dev/running-expo-in-windows-subsystem-for-linux-wsl2-425f6fd7838e

This feature is complete when 
- Access a dev server with create-react-app on local network
- Access Expo dev apps on local network

Optional features
- Options to choose which ports are open

**Comment by patrick330602** [comment]
Have you tried to built-in `localhostForward` feature?

**Comment by WSLUser** [comment]
I imagine you'll need something like this:

```
 # /etc/rc.local runs as root by default
# if you run these yourself add 'sudo' to the beginning of each command 
 $ sysctl -w net.ipv4.conf.all.route_localnet=1
$ iptables -t nat -I PREROUTING -p tcp -j DNAT --to-destination 127.0.0.1 
```

except instead of loopback (I got this from the wsl2-hack repo), it's doing other forwarding of the actual wsl2 IP.

**Comment by patrick330602** [comment]
As wslu entering maintainance, this feature will not be added.
