### ISSUE TITLE
wslview cannot open paths with spaces

### ISSUE THREAD

**Issue by DanKaplanSES** [wslutilities/wslu#230]
**Background Information:**
 - Build: wslu v3.2.2-1; wslview v10
 - WSL: Ubuntu 20.04.4 LTS
 - Version: [e.g. 1.5] no idea what this is asking for.

**Describe the bug**
If a path has spaces, it cannot be opened by `wslview`

**To Reproduce**
```bash
touch 'contains spaces.txt'
wslpath contains\ spaces.txt
wslview $(wslpath -w contains\ spaces.txt)
```
Output:
```
Start : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:128
+ ... etEncoding(437); Start "\\wsl$\Ubuntu\home\...\containsspaces.txt"
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```
Notice that there are no spaces in the file name.

This works correctly:
```bash
touch no_spaces.txt
wslview $(wslpath -w no_spaces.txt)
```

**Expected behavior**
Regardless of spaces, the file should open.

**Additional context**
This is a **really** old bug. Exists in version 2.

**Comment by patrick330602** [comment]
You could use `wslview "$(wslpath -w no_spaces.txt)"` for this for now. The bug is now noted.

**Comment by DanKaplanSES** [comment]
> You could use `wslview "$(wslpath -w no_spaces.txt)"` for this for now. The bug is now noted.

Good find. But I think you used the wrong file in your example.

**Comment by DanKaplanSES** [comment]
@vbrozik 

> This is because shell performs word/field splitting and filename expansion on the result of the command substitution.

Today I learned... that can probably explain a whole lot of issues I've been having with complex command chaining/substitution. This implies I could use command substitution to provide more than one argument for command, an option I didn't realize was available.

Thanks for the information.
