### ISSUE TITLE
wslvar returns "Parameter format not correct - /c" twice when ran

### ISSUE THREAD

**Issue by shinji257** [wslutilities/wslu#231]
**Background Information:**
 - Build: 22593.1
 - WSL: Ubuntu 20.04 and 22.04
 - Version: 0.58.0.0

**Describe the bug**
When running wslvar it is currently returning "Parameter format not correct  - /c" twice.  On 20.04 it does it no matter what and on 22.04 only when you have it translate a windows environment variable.

**To Reproduce**
On 20.04 just run it without options.  On 22.04 run it with an environment variable like localappdata

**Expected behavior**
Either produce help context or output just the result.

**Additional context**
Currently the script still seems to work fine regardless of the messages.  The messages are actually generated by chcp when the script calls the binary from the Windows side.  I'm on Windows beta branch right now and there is a new WSL preview currently.  I suspect it is a bug with the program running in WSL in general.

As of right now I commented out the function and the calls to the same function responsible for running chcp and there seems to be no negative impact to its operation as it still worked fine previously even with the issue.  However, you may be able to provide some inside as to why the codepage is being changed?

**Comment by patrick330602** [comment]
Hi,

This is currently fixed in wslu 3.2.4 LTS. Unfortunately, right now I encountered some issues packaging the Ubuntu version, and I am still working on the packaging. Once the package is done, I will notify here.

**Comment by shinji257** [comment]
Yea. That's my ticket over there to see if the dev could do something with it. Looks like they did and I'll be waiting for the fix.

**Comment by shinji257** [comment]
Thank you. I'll be waiting for the update.

**Comment by patrick330602** [comment]
Can you try this one and whether it solves your issue? https://launchpad.net/~wslutilities/+archive/ubuntu/wslu

**Comment by ImIOImI** [comment]
@patrick330602 I just tested this after adding and updating that repo and it didn't resolve the issue:

```
❯ wslvar
Parameter format not correct - /c
Parameter format not correct - /c
```

I tried this in zsh and bash just in the oft chance it made a difference, but it doesn't.

**Comment by patrick330602** [comment]
Interesting. Can you show the `wslvar --version`?

**Comment by shinji257** [comment]
Tested on Ubuntu 20.04 with your PPA and it works fine here.  Curiously it held the package back because it suddenly wanted to install desktop-file-utils but I don't know why.  The wasn't required for the one from the official repo but that change may have happened a long time ago as well.

```
┏[shinji]
┖[~]
   lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
┏[shinji]
┖[~]
   wslvar --version
wslu v3.2.4-1; wslvar v03
┏[shinji]
┖[~]
   wslvar
[error] No Input. Aborted.
┏[shinji][x21]
┖[~]
   wslvar localappdata
C:\Users\shinj\AppData\Local
```

**Comment by ImIOImI** [comment]
@shinji257 thanks for that heads up, I missed it. Resolved that issue and was able to update properly to the latest. Thanks @patrick330602 !

**Comment by patrick330602** [comment]
> Curiously it held the package back because it suddenly wanted to install desktop-file-utils but I don't know why.

The one in Ubuntu repo does not require `desktop-file-utils`, but PPA one requires one. Since I left Canonical a few months ago, the Ubuntu repo one is unmaintained and outdated for some versions. Please use PPA one from now on.

And since the update fixes you guys' problem, I will close this issue.
