### ISSUE TITLE
The certificate of ‘pkg.wslutiliti.es’ is not trusted.

### ISSUE THREAD

**Issue by PylotLight** [wslutilities/wslu#237]
Hi,

I am trying to install the utility but getting this error. I am on a company machine with SSL packet inspection which may be causing certificate issues, but not sure if's there's any way to validate if that's the issue or get around it if it is.

wget -O - https://pkg.wslutiliti.es/public.key | sudo tee -a /etc/apt/trusted.gpg.d/wslu.asc
--2022-07-20 15:25:18--  https://pkg.wslutiliti.es/public.key
Resolving pkg.wslutiliti.es (pkg.wslutiliti.es)... 139.162.37.22
Connecting to pkg.wslutiliti.es (pkg.wslutiliti.es)|139.162.37.22|:443... connected.
ERROR: The certificate of ‘pkg.wslutiliti.es’ is not trusted.
ERROR: The certificate of ‘pkg.wslutiliti.es’ doesn't have a known issuer.

**Comment by patrick330602** [comment]
Interesting, I tested locally here and it is fine for me. 
![Screenshot 2022-07-20 at 14 02 20](https://user-images.githubusercontent.com/15316889/179908251-bbe2eaef-b662-4b49-875c-3b25612e24b7.png)
Could you check whether you have update to the latest versions of packages? (For example, outdated `ca-certificate` could cause the certificate to be not trusted, especially Let's Encrypted updated how they issue the certificate in recent months)

**Comment by PylotLight** [comment]
Not sure what I did but seems fixed now, was able to install.
