### ISSUE TITLE
wslview is not enabled

### ISSUE THREAD

**Issue by rwseitz3060** [wslutilities/wslu#238]
**Background Information:**
 - Build: [e.g. 17704]
 - WSL:  Kubuntu 22.04
 - Version: [e.g. 1.5]

**Describe the bug**
wslview is not enabled; this happened after installing samba client in Kubuntu 22.04

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by patrick330602** [comment]
Hi,

Can you clarify the problem? You should install `wslu` if you haven't (Please refer to this for why: https://github.com/wslutilities/wslu/discussions/234)
