### ISSUE TITLE
Make FFMPEG an optional dependency in lieu of ImageMagick

### ISSUE THREAD

**Issue by WSLUser** [wslutilities/wslu#239]
ImageMagick has rather poor performance as has been been demonstrated by TUI library projects like chafa (who is actually considering the switch to FFMPEG) and notcurses and as noted here brings in a ton of extra dependencies . So since you plan on making ImageMagick an optional dependency: https://github.com/wslutilities/wslu/issues/236, it would then make sense to offer an alternative in addition to ImageMagick. This is where https://github.com/FFmpeg/FFmpeg comes in. I hope when you have time, you'll consider using FFMPEG for this project and not just ImageMagick.

**Comment by patrick330602** [comment]
After quick checking, I will add this as part of wslu 4.0. Will work on this.

**Comment by WSLUser** [comment]
Adding https://github.com/marioroy/ffmpeg-on-clear-linux so we don't have to leave Clear Linux out of the mix.

**Comment by patrick330602** [comment]
I will have to move this to 4.1... Right now I will be focus on delivering the version 4.0 first.

**Comment by WSLUser** [comment]
Yes hoping you'll release 4.0 soon.

**Comment by WSLUser** [comment]
I noticed you added some preliminary code to use FFMPEG. Looking forward to testing it out once you've done your own testing and finalize the code.
