### ISSUE TITLE
reg.exe & chcp.com Application Error when running wslview from putty

### ISSUE THREAD

**Issue by 4nqyi** [wslutilities/wslu#242]
**Background Information:**
 - Windows Version: [Windows 10]
 - Windows Build: 19044. 1889
 - WSL: Ubuntu 18.04.2 LTS
 - Version: wslu v3.2.4-1; wslview v10

**Describe the bug**
Just started receiving these errors today when launching wslview from my putty session. No issues when launching from windows terminal. The reg.exe will pop up 3 times followed by a chcp.com application error. The address eventually opens in my default windows browser which is chrome.

![image](https://user-images.githubusercontent.com/11065729/187527530-3f3631ec-1619-4b21-9081-9e93da9c8179.png)
![image](https://user-images.githubusercontent.com/11065729/187527548-40df43cc-75b9-4627-bf09-3df669574119.png)

**To Reproduce**
- ssh to your wsl instance via putty
- run _wslview https://github.com/wslutilities/wslu_

**Expected behavior**
URL lauch in my windows browser without any popup errors.

**Comment by patrick330602** [comment]
Just try to confirm, are you using putty or wsltty? Thanks

**Comment by 4nqyi** [comment]
> Just try to confirm, are you using putty or wsltty? Thanks

Putty

**Comment by patrick330602** [comment]
After some investigation, this is possibly related: https://github.com/microsoft/terminal/issues/13340

> That message is usually caused by the console host process (conhost.exe) exiting before the client application can even spawn

that is possibly caused by your `conhost.exe`, but definitely not related to WSL itself. it is better to report to putty or windows terminal (https://github.com/microsoft/terminal/issues , they also accept conhost-related bugs)

**Comment by 4nqyi** [comment]
@patrick330602 you're right. its not limited to wslu. Seems to be a windows issue.  Thanks for looking.

I tried opening the default browser using this command I get the same errors.
`xdg-open https://stackoverflow.com`

**Comment by 4nqyi** [comment]
just an update, a reboot fixed the issue.
