### ISSUE TITLE
wslu tools report errors when automount root is quoted in wsl.conf

### ISSUE THREAD

**Issue by mkielar** [wslutilities/wslu#247]
**Background Information:**
 - Windows Version: `Windows 11 Pro 21H2`
 - Windows Build: `22000.1042`
 - WSL: `fedoraremix` running on `WSL1`
 - Version: `36.0.5`
 - Output from `wsl --version`:
   ```
   wsl --version
   WSL version: 0.66.2.0
   Kernel version: 5.15.57.1
   WSLg version: 1.0.42
   MSRDC version: 1.2.3401
   Direct3D version: 1.606.4
   DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
   Windows version: 10.0.22000.1042
   ```
- Output from `dnf info wslu`:
  ```
  Installed Packages
  Name         : wslu
  Version      : 4.0.0
  Release      : 1
  Architecture : noarch
  Size         : 251 k
  Source       : wslu-4.0.0-1.src.rpm
  Repository   : @System
  From repo    : copr:copr.fedorainfracloud.org:wslutilities:wslu
  (truncated for brevity)
  ```
**Describe the bug**
When the `root` property contains a quoted value in `/etc/wsl.conf`, `wslu` tools show errors when ran, such as below:
```
→ wslupath --help
/usr/bin/wslupath: line 207: "/"/c/Windows/System32/reg.exe: No such file or directory
/usr/bin/wslupath: line 207: "/"/c/Windows/System32/reg.exe: No such file or directory
wslupath - Part of wslu, a collection of utilities for Linux Subsystem for Windows (WSL)
Usage: wslupath [-dOr] [-D|-A|-T|-S|-W|-s|-su|-H|-P|...NAME...]
wslupath [-h|-v|-R]

For more help for wslupath, please use the command `man wslupath` or visit the following site: https://wslutiliti.es/wslu/man/wslupath.html.
For overall help, you can use the command `man wslu` or visite the following site: https://wslutiliti.es/wslu.
```

```
→ wslact --help
/usr/bin/wslact: line 207: "/"/c/Windows/System32/reg.exe: No such file or directory
/usr/bin/wslact: line 207: "/"/c/Windows/System32/reg.exe: No such file or directory
wslact - Part of wslu, a collection of utilities for Linux Subsystem for Windows (WSL)
Usage: wslact COMMAND ...

For more help for wslact, please use the command `man wslact` or visit the following site: https://wslutiliti.es/wslu/man/wslact.html.
For overall help, you can use the command `man wslu` or visite the following site: https://wslutiliti.es/wslu.
```

**To Reproduce**
1. Configure `/etc/wsl.conf` like this:
    ```
    [automount]
    root = "/"
    options = "metadata"
    ```
    Make sure the value of the `root` property is wrapped in `"` quotes.
2. Run `wslact --help`
3. Observe the `No such file or directory` warnings.

**Expected behavior**
`wslu` tools should understand quoted values in `wsl.conf` and act accordingly.

**Additional context**
1. When changing the configuration in `wsl.conf` to `root = /` (unquoted), the issue disappears.
2. Despite very simple workaround in pt.1 above, I still believe this is a bug in `wslu` implementation. If you refer to [the `wsl.conf` documentation][wslconfdoc], it does not clearly define what the format of the file is, and what syntax should be used. It only shows examples on how to use specific configuration sections, and in these examples the `root` property is indeed presented as unquoted. **However**, [the example][wslconfexample] also shows that the `options` property of the `[automount]` section **can be quoted**, and that - in my opinion - suggest that **any value in the file can be quoted** and it should be handled properly.

[wslconfdoc]: https://learn.microsoft.com/en-us/windows/wsl/wsl-config#wslconf
[wslconfexample]: https://learn.microsoft.com/en-us/windows/wsl/wsl-config#example-wslconf-file

**Comment by patrick330602** [comment]
Thank you for the report. I will fix the issue in 4.1.

**Comment by dj-rabel** [comment]
Hello @patrick330602. Not sure if opening a new issue would have been better, but the script failes as well, if one sets the default user to root in wsl.conf like so:
```
[user]
default = root
```
![image](https://user-images.githubusercontent.com/4653214/197576079-ed9e18b3-740f-449a-a1ea-a3561ec2692b.png)

I was able to temporarily fix it for me, by changing the awk line inside the "interop_prefix" function to
`tmp=$(awk -F '=' '/^\s*root/ {print $2}' /etc/wsl.conf | awk '{$1=$1;print}')`

Hope this helps ♥

**Comment by 2pl** [comment]
Hi @patrick330602 I also noticed that the awk pattern for root does not ignore commented lines ie adding something like the below in /etc/wsl.conf will trigger similar errors as described above by @mkielar

```
# [automount]
# root = /whatever
```
I guess the modified awk interop_prefix function suggested by @dj-rabel should fix this as well.

**Comment by patrick330602** [comment]
fixed in dev
