### ISSUE TITLE
Can't install/update wslutilities package on W10 due to certificate not being trusted

### ISSUE THREAD

**Issue by j-ilden** [wslutilities/wslu#251]
I can't update the package on ArchWSL.

ERROR: The certificate of ‘pkg.wslutiliti.es’ doesn't have a known issuer. Manual installation of the publickey step can't be followed. I don't think it's wise to workaround with insecure way of doing it. 

## pacman output:
`❯ sudo pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra                                                           1721.5 KiB   911 KiB/s 00:02 [-------------------------------------------------------] 100% community                                                          7.1 MiB   766 KiB/s 00:09 [-------------------------------------------------------] 100% wslutilities.db failed to download
error: failed retrieving file 'wslutilities.db' from pkg.wslutiliti.es : SSL certificate problem: unable to get local issuer certificate
error: failed to synchronize all databases (download library error)`

[The first step of the installation for Arch](https://wslutiliti.es/wslu/install.html) doesn't work either. 
`❯ wget https://pkg.wslutiliti.es/public.key
--2022-10-20 13:14:16--  https://pkg.wslutiliti.es/public.key
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving pkg.wslutiliti.es (pkg.wslutiliti.es)... 139.162.37.22
Connecting to pkg.wslutiliti.es (pkg.wslutiliti.es)|139.162.37.22|:443... connected.
ERROR: The certificate of ‘pkg.wslutiliti.es’ is not trusted.
ERROR: The certificate of ‘pkg.wslutiliti.es’ doesn't have a known issuer.`

**Comment by SuperSandro2000** [comment]
Try updating ca-certificates

**Comment by j-ilden** [comment]
Done and resolved.
