### ISSUE TITLE
wslview does not support URL fragments (#) for local files

### ISSUE THREAD

**Issue by DenialAdams** [wslutilities/wslu#252]
**Background Information:**
 - Windows Version: Windows 11 22H2
 - Windows Build: build 22621.674
 - WSL: ArchWSL 22.10.16.0 
 - Version: wslu v3.2.4-1; wslview v10

**Describe the bug**
`wslview "myfile.html"` works with no problem. `wslview "myfile.html#fragment"` results in the following error:

```
Start : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:128
+ ... oding(932); Start "file:///root/roland/tarpaulin-report.html#rolandc/ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

**To Reproduce**
`wslview "myfile.html#fragment"`

**Expected behavior**
Fragment survives and is passed to the browser. Maybe this isn't possible?

**Additional context**
Thank you very much for `wslview`!

**Comment by DenialAdams** [comment]
Updated the title to mention local files, because wslview "https://google.com#fragment" seems to work as expected

**Comment by patrick330602** [comment]
Hi, 

Can you paste the result for `wslview --debug "myfile.html#fragment"`? Thanks!

**Comment by DenialAdams** [comment]
> Hi,
> 
> Can you paste the result for `wslview --debug "myfile.html#fragment"`? Thanks!

```
# wslview --debug "tarpaulin-report.html#rolandc"
[debug] Showing debug output.
Start : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:128
+ ... xt.Encoding]::GetEncoding(932); Start "tarpaulin-report.html#rolandc"
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

**Comment by patrick330602** [comment]
After some experiments, this would be impossible as `#` is a valid character in file name in both Linux and Windows which will cause problem in file reading. Unfortunately, this will not be fixed.
