### ISSUE TITLE
wslu is not taking DESTDIR into account when loading config file

### ISSUE THREAD

**Issue by SuperSandro2000** [wslutilities/wslu#264]
### Windows Version

Windows 11

### Windows Build Number

10.0.22621.1105

### WSL Version

WSL 2

### Distro Version

NixOS

### WSL Utilities Version

4.1.1

### Describe the bug

NixOS is using DESTDIR variable to install the conf file into a none standard location (eg ``/nix/store/f9w6sa74xk0hymrbz2mrm4r9hfvns6fp-wslu-4.1.1/etc/wslu/conf``). By default utilities like wslvar will not find it and miss a default value for ``WSLVAR_DEFAULT_VARTYPE``, those a command like ``wslvar USERNAME`` fails with ``[error] Invalid variable type. Aborted.``.

### Steps to Reproduce

Run the following on NixOS unstable in WSL.
```
$ wslvar USERNAME
[error] Invalid variable type. Aborted.
```

### Expected behavior

DESTDIR should be used to find the fallback config in the nix store if the usual locations do not yield a result.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patrick330602** [comment]
Interesting... I will take a look recently
