### ISSUE TITLE
Opens Windows File Explorer instead of browser

### ISSUE THREAD

**Issue by MartinEmrich** [wslutilities/wslu#267]
### Windows Version

Windows 10

### Windows Build Number

19045.2604

### WSL Version

WSL 2

### Distro Version

Debian (bullseye)

### WSL Utilities Version

3.2.4-1 (latest from package repository)

### Describe the bug

(Probably) Since the latest WSL update this week, wslview no longer opens the link in the Windows default browser, but it opens a new Windows File Explorer window on the current working directory.

### Steps to Reproduce

run e.g. `wslview "https://www.google.com"`

### Expected behavior

I expect a new tab in Edge opening Google.

### Additional context

````
$ wsl.exe --version
WSL-Version: 1.1.3.0
Kernelversion: 5.15.90.1
WSLg-Version: 1.0.49
MSRDC-Version: 1.2.3770
Direct3D-Version: 1.608.2-61064218
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows Version: 10.0.19045.2604
````

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xpeoh** [comment]
We are seeing this issue as well.

**Comment by lithammer** [comment]
Manually updating to 4.4.1 solved the issue for me. It's a bit unfortunate that the Debian package is still on 3.2.4. So I added the Ubuntu PPA which less than ideal, but solved the problem.

**Comment by MartinEmrich** [comment]
Yes, installing from source worked here, too.

**Comment by Physikbuddha** [comment]
Another dev and I are experiencing the same issue. Yet another developer reported that he can open URLs just fine.  
All of us are using Windows 10.

However, we noticed that the "broken" systems are using Debian on WSL2, while the working installation is running Ubuntu instead.

It might help if you report which Linux distribution you are using.

**Comment by xpeoh** [comment]
We're using Debian on WSL2.

**Comment by patrick330602** [comment]
Thank you for the report. Will try to look into it this weekend.

**Comment by karlcloudy** [comment]
This is also not working on openSUSE Tumbleweed - that said, the version available on the repo there is also only 3.2.4, so I suspect this is why I have the issue as well.
```shell
$ zypper up wslu
Loading repository data...
Reading installed packages...
No update candidate for 'wslu-3.2.4-26.12.noarch'. The highest available version is already installed.
Resolving package dependencies...
Nothing to do.
```

**Comment by GeorgeGomez** [comment]
I am using WSL with Ubuntu and the identical WSL versions as the OP and also experiencing File Explorer opening up instead of Chrome, my default browser.

I do have 2 Ubuntu distributions, I will call them OG (working) and New (bug), here are the wslview versions FYI:

**OG version :** wslu v2.3.6; wslview v06 (working like a champ)
**New version:** wslu v3.2.4-1; wslview v10 (opening up file explorer)

I will either manually install or go to the v2.3.6 version via the package manager to fix the bug. Thank you.

**Comment by HenrikStanley** [comment]
I am seeing the same issue using ArchLinux.
When looking into the https://pkg.wslutiliti.es/arch/ the newest version is 3.2.4-0 which does match the challenge of having the issue while not on the v4.x

**Comment by patrick330602** [comment]
Sorry for late updates. As people point out, multiple packages are still using old releases. I am right now upgrading all the rest of the packages to the latest version, and currently Arch Linux is completed. I will update once the rest of them are updated.

**Comment by patrick330602** [comment]
@karlcloudy which repo are you using? I double checked and wslu 4.1.1 exists: https://build.opensuse.org/package/binaries/home:wslutilities/wslu/openSUSE_Tumbleweed

**Comment by patrick330602** [comment]
@karlcloudy I just notice there are problems with OpenSUSE Build Service. Please delete the old repository:
```bash
sudo zypper repos #list repos and find the corresponding Alias/#
sudo zypper rr <Alias/#>
```

And then add the new one:

```bash
sudo zypper addrepo https://copr.fedorainfracloud.org/coprs/wslutilities/wslu/repo/opensuse-tumbleweed/wslutilities-wslu-opensuse-tumbleweed.repo
sudo zypper up
sudo zypper in wslu
```

**Comment by patrick330602** [comment]
debian buster and bullseye completed update to wslu 4.1.1.

**Comment by patrick330602** [comment]
I will close this for now, if you still have issue, I will re-open this

**Comment by sirianni** [comment]
Thanks @patrick330602 I am seeing a similar issue on 4.1.1 but it only happens for certain applications.  For example, the `gh` CLI `gh pr open --web` opens up an explorer window instead of a browser.  When I run `wslview http://github.com` it works.  So perhaps it's a MIME issue and not in wslview itself?  It's likely a different problem but I'd appreciate any pointers you have on debugging this.

**Comment by crramirez** [comment]
Maybe you can modify wslview locally and put set -x the see what wslview is
receiving
