### ISSUE TITLE
wslview not openeing links with limited access

### ISSUE THREAD

**Issue by marcinbjorn** [wslutilities/wslu#268]
### Windows Version

Windows 10

### Windows Build Number

19044

### WSL Version

WSL 2

### Distro Version

Ubuntu 20.04

### WSL Utilities Version

4.1.1

### Describe the bug

I'm trying to open websites with access control list limited only to few public IPs. I'm getting this error
```
wslview http://210.210.210.210
Start : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:128
+ ... ystem.Text.Encoding]::GetEncoding(850); Start "http\210.210.210.210"
+                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

Edit:
Made temporary fix by commenting out body of `function url_validator` (line 461) and return 0

Edit2:
Found what was the issue, curl fail with error `curl: (60) SSL certificate problem: self signed certificate` flag `--insecure` solves issue
```
function url_validator {
 content=$(curl --head --insecure --silent "$*" | head -n 1)
 if [ -n "$content" ]; then
    return 0
 else
    return 1
 fi
}
```
Websites that I'm accessing have very high latency, in my case curling takes extra 1-2 seconds, I'm rather skip validation at all

### Steps to Reproduce

wslview [ not existing website ]

### Expected behavior

Whenever wslview sees http:// or https:// at the beginning of link it should trust user and open link without verifying it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CoeJoder** [comment]
I am having the same problem.  In my case, ProxMox (a hypervisor) generates one-time use `noVNC` links in my shell script for remote access, and I want to open those links using `wslview`.  This used to work on old versions of `wslview` but now it's broken.
Eg.
```
wslview https://proxmox.local:8006/?console=kvm&novnc=1&vmid=100&vmname=mintbox
```
This does not longer work, I get the "Not found" error message as above.  After some testing, I see that `wslview` refuses to open any links which it deems as not leading to a valid website.  I'm not sure why this behavior would ever be wanted.

**Comment by patrick330602** [comment]
Add a new param in dev for `wslview` as -s, --skip-validation-check and will release as part of wslu 4.2.0.

**Comment by JaZo** [comment]
The fix for this issue does not address the one-time-use URL issue, so I've opened #301 for that.

**Comment by MakerTim** [comment]
> Checking the URL first also leads to a problem if a cli utility like `drush` is creating one-time login link. Dispatching a HEAD request on a one-time-use URL before opening will immediatly invalidate it. WSL view should be able to validate an URL (regex) without checking if it's returning any content. It should ideally be provided as an optional flag or at least be skippable.

You can strip the `/login` from `drush uli` as quick workaround.
