### ISSUE TITLE
wslfetch and wslsys incorrectly report WSL1 when run over SSH to WSL2 installation

### ISSUE THREAD

**Issue by ostrich** [wslutilities/wslu#272]
### Windows Version

Windows 11

### Windows Build Number

22621.1413

### WSL Version

WSL 2

### Distro Version

Debian Bullseye

### WSL Utilities Version

3.2.4-1

### Describe the bug

`wslfetch` and `wslsys` both incorrectly report WSL1 when run in an SSH session to a WSL2 installation.

### Steps to Reproduce

1. SSH to your WSL2 installation
2. Run `wslfetch` and `wslview`
3. Observe that they incorrectly report you are running WSL1

### Expected behavior

They should report WSL2

### Additional context

Running each command locally correctly reports WSL2.

To SSH into WSL, I am using the port forwarding technique [described here](https://jmmv.dev/2022/02/wsl-ssh-access.html) rather than the bash.exe shell replacement technique [described here](https://www.hanselman.com/blog/the-easy-way-how-to-ssh-into-bash-and-wsl2-on-windows-10-from-an-external-machine) (if that matters).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patrick330602** [comment]
Hi, can you try to upgrade to the latest verison of wslu 4.1.1? Thanks

**Comment by ostrich** [comment]
Just upgraded, same issue

ostrich@ostrich5 ~> apt info wslu
Package: wslu
Version: 4.1.1-1debian1

**Comment by ostrich** [comment]
I also note that over SSH, `wslsys` reports `SystemD Status: N/A` while running locally correctly reports `SystemD Status: enabled`

**Comment by patrick330602** [comment]
This is potentially related to the default behavior of WSL, there when SSH into the WSL instance will not load the WSL binary, which leads to `wslu` not working.

Right now I cannot verify this issue due to my laptop's motherboard got fried 😅

**Comment by ostrich** [comment]
I think it's along those lines. I looked at function `wslu_get_wsl_ver` in `wslu-header` and it calls reg.exe. When I try to run reg.exe over SSH, it fails.

**Comment by patrick330602** [comment]
This is unfortunately something I am unable to help... If SSH is unable to load Windows binary, wslu will just not work.
