### ISSUE TITLE
Certificat expired on https://wslutiliti.es

### ISSUE THREAD

**Issue by dsx** [wslutilities/wslu#276]
### Windows Version

Windows 10

### Windows Build Number

N/A

### WSL Version

Not Applicable

### Distro Version

N/A

### WSL Utilities Version

N/A

### Summary
TLS certificate on https://wslutiliti.es expired:
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 273517017002948175601068484173951654909048 (0x323cb5555a4bec5a61cf3e4f82f99135478)
    Signature Algorithm: SHA256-RSA
        Issuer: C=US,O=Let's Encrypt,CN=R3
        Validity
            Not Before: Jan 25 21:53:55 2023 UTC
            Not After : Apr 25 21:53:54 2023 UTC
        Subject: CN=wslutiliti.es
```

### Steps to Reproduce

1. Open https://wslutiliti.es in a browser

### Expected behavior

Certificate is not expired.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patrick330602** [comment]
It is temporarily solved with no https. I will put up a proper fix tonight

**Comment by patrick330602** [comment]
Finally solved with some server migration
