### ISSUE TITLE
Arch keyring package signing key has expired

### ISSUE THREAD

**Issue by BMurri** [wslutilities/wslu#278]
### Windows Version

Windows 11

### Windows Build Number

22621

### WSL Version

WSL 2

### Distro Version

ManjaroLinux 23.0.0

### WSL Utilities Version

unknown

### Describe the bug

The `WSL Utilities Package Signing Key <contact@wslutiliti.es>` signing key has expired.

### Steps to Reproduce

1. Go to terminal
2. Type `sudo pacman -Syu` followed by the `Enter` key
3. Type the password requested by sudo
4. See the following error message x2 followed by the subsequent error message

 > error: wslutilities: signature from "WSL Utilities Package Signing Key <contact@wslutiliti.es>" is unknown trust
 > error: failed to synchronize all databases (invalid or corrupted database (PGP signature))

### Expected behavior

updating the packages on my system would succeed.

### Additional context

running `pacman-key -l` produces the following:

 > pub   rsa4096 2021-06-12 [SC] [expired: 2023-06-12]
 >       B9BBB9AFF017C6F638DEF280A2861ABFD897DD37
 > uid           [ expired] WSL Utilities Package Signing Key <contact@wslutiliti.es>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patrick330602** [comment]
Thanks for the report, I will update it tonight.

**Comment by bobby4k** [comment]
As temporary 

sudo vim /etc/pacman.conf
```
SigLevel = Never
#LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required
```

**Comment by patrick330602** [comment]
The key for the Arch Linux is updated.

You should do the following as root:
```bash
pacman-key -d A2861ABFD897DD37

#download the new key
wget https://pkg.wslutiliti.es/public.key
pacman-key --add public.key

#locally sign the new key
pacman-key --lsign-key 2D4C887EB08424F157151C493DD50AA7E055D853
```

**NOTE**: This will also affect Debian related builds. I will try to update that tomorrow since it's already 3am in the morning.

**Comment by willgladstone** [comment]
Thanks @patrick330602 for getting to this so fast. Will you let us know when the debian builds are updated?

**Comment by patrick330602** [comment]
> Thanks @patrick330602 for getting to this so fast. Will you let us know when the debian builds are updated?

@willgladstone yep, I will also post updates on Mastodon at https://fosstodon.org/@wslutilities, on Twitter at https://twitter.com/wslutilities and directly on Blog at https://blog.wslutiliti.es

**Comment by patrick330602** [comment]
Debian and Kali builds are also updated: https://blog.wslutiliti.es/2023/06/16/key-update/index.html
