### ISSUE TITLE
PGP key for ArchLinux no longer matches install instructions.

### ISSUE THREAD

**Issue by HenrikStanley** [wslutilities/wslu#279]
### Windows Version

Windows 11

### Windows Build Number

22621.1702

### WSL Version

WSL 2

### Distro Version

ArchLinux

### WSL Utilities Version

v4.1.1-1

### Describe the bug

When running an install with pacman or paru on Arch, the PGP key signature no longer matches the one from the install instructions.

The install instructions uses a key with signature: A2861ABFD897DD37
When trying to update now, the key is unknown and references a key with ID: 2D4C887EB08424F157151C493DD50AA7E055D853

Was the certificates updated?

```shell
 paru -Syuu
error: wslutilities: key "2D4C887EB08424F157151C493DD50AA7E055D853" is unknown
:: Import PGP key 2D4C887EB08424F157151C493DD50AA7E055D853? [Y/n] y
error: key "2D4C887EB08424F157151C493DD50AA7E055D853" could not be looked up remotely
:: Synchronizing package databases...
 core downloading...
 extra downloading...
 community downloading...
 wslutilities downloading...
error: wslutilities: key "2D4C887EB08424F157151C493DD50AA7E055D853" is unknown
:: Import PGP key 2D4C887EB08424F157151C493DD50AA7E055D853? [Y/n] y
error: key "2D4C887EB08424F157151C493DD50AA7E055D853" could not be looked up remotely
error: failed to synchronize all databases (invalid or corrupted database (PGP signature))
```

### Steps to Reproduce

1. Run: pacman -Syuu
2. Error occurs. 

### Expected behavior

The key that pacman / paru should use for the WSLU repo should match the A2861ABFD897DD37 fingerprint.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patrick330602** [comment]
Just changed yesterday:
https://github.com/wslutilities/wslu/issues/278#issuecomment-1589870056
