### ISSUE TITLE
[Feature request] Add expections in wslview

### ISSUE THREAD

**Issue by maicol07** [wslutilities/wslu#280]
### Windows Version

Windows 11

### Windows Build Number

23486

### WSL Version

WSL 2

### Distro Version

Ubuntu 22.04

### WSL Utilities Version

4.1.1

### Describe the bug

When wslview is set as defaut browser it can be useful to have certain exclusions to be open in WSL. Maybe some sort of URL schemes and websites or regex in a config file?

### Steps to Reproduce

Set as default browser and everything is opened via wslview.

### Expected behavior

Not a bug

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patrick330602** [comment]
`wslu` has entered the maintenance stage; currently I am not accepting any new feature request.
