### ISSUE TITLE
Document how to get the latest wslu

### ISSUE THREAD

**Issue by DanKaplanSES** [wslutilities/wslu#288]
### Windows Version

Windows 10

### Windows Build Number

19045.3448

### WSL Version

WSL 2

### Distro Version

Ubuntu 22.04.2 LTS

### WSL Utilities Version

3.2.3-0ubuntu3

### Describe the bug

[I thought I had the latest version of WSLU](https://github.com/microsoft/WSL/issues/10084#issuecomment-1742239465) because `apt-get` and `show` said so, even after running `apt update`. I only discovered I was using an older version by coincidence: I was going to create an issue and noticed the info at the top of this template:

>     ATTENTION!
> 
>     Built-in versions of wslu in Ubuntu are no longer supported by me.
> 
>     If you have problems, please:
> 
>        1. Report to the Ubuntu WSL team; or
>        2. Try the PPA version of WSL here: https://launchpad.net/~wslutilities/+archive/ubuntu/wslu
> 
>     Usually The PPA version of wslu will address most of your problems.

I think this is important information to anyone using a wslu command. Ideally, Ubuntu/WSL2 would come with the latest version, but I'm inferring they aren't willing to do that?

If that's not an option, I think the quoted text should be more prevalent. I'd like to suggest these changes:

- [ ] Ask Ubuntu to upgrade to the latest WSLU(?)
- [ ] Add this information to the top of the README.md file
- [ ] Put this information in the CONTRIBUTING.md file
- [ ] Ask [Microsoft/WSL](https://github.com/microsoft/WSL) if they would be willing to update WSL to contain the latest WSLU
- [ ] Ask [Microsoft/WSL](https://github.com/microsoft/WSL) if they would be willing to put this information in their [CONTRIBUTING.md file](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md)
- [ ] Semi-related: update the README.md file to list every WSLU command to improve the chances of users finding this repository. Searching "github wslpath" doesn't list this repository on the first page of results, but it does list a bunch of unofficial repositories and [the official WSL repository](https://github.com/microsoft/WSL). 

### Steps to Reproduce

n/a

### Expected behavior

When I install WSL, it comes with the latest stable version of WSLU.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patrick330602** [comment]
> Ask Ubuntu to upgrade to the latest WSLU(?)
> Ask [Microsoft/WSL](https://github.com/microsoft/WSL) if they would be willing to update WSL to contain the latest WSLU
> Ask [Microsoft/WSL](https://github.com/microsoft/WSL) if they would be willing to put this information in their [CONTRIBUTING.md file](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md)

These are little bit not possible, but I do hope if Microsoft could pick this up ( But unlikely due to this project is licensed under GPLv3)

> Add this information to the top of the README.md file
> Put this information in the CONTRIBUTING.md file

I do can do this two

> Searching "github wslpath" doesn't list this repository

This is because `wslpath` is the tool built by Microsoft while `wslupath` that is shipped by `wslu`. These are different tools; and `wslupath` would call `wslpath` to do some of the work currently.
