### ISSUE TITLE
USE XDG_CACHE instead of ~/.config/wslu

### ISSUE THREAD

**Issue by woutervh** [wslutilities/wslu#290]
### Windows Version

Windows 11

### Windows Build Number

latest

### WSL Version

WSL 2

### Distro Version

Almalinux

### WSL Utilities Version

wslu v4.1.1-1

### Describe the bug

files are being created in a hardcoded ~/.config/wslu:

- baseexec  
- oemcp 
- triggered_time

but these are not config-files. 
rather cache-files or state

To avoid hardcoding: better use:
XDG_CONFIG_HOME (default to ~/.config)

or better:
XDG_STATE_HOME  (default to~/.local/state)
XDG_CACHE_HOME  (default to~/.cache)

### Steps to Reproduce

ls ~/.config/wlu

- baseexec  
- oemcp 
- triggered_time

### Expected behavior

ls ~/.cache/wlu

- baseexec  
- oemcp 
- triggered_time

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patrick330602** [comment]
Thanks for the report and currently working on it.
