### ISSUE TITLE
file uri not decoded by wslview

### ISSUE THREAD

**Issue by champignoom** [wslutilities/wslu#295]
### Windows Version

Windows 10

### Windows Build Number

19045.3570

### WSL Version

WSL 2

### Distro Version

Ubuntu 22.04

### WSL Utilities Version

wslu v3.2.3-1; wslview v10

### Describe the bug

escape sequence like `%20` in a file uri is not properly decoded by wslview.

### Steps to Reproduce

`wslview 'file:///home/me/a%20b.txt'`, then `a%20b.txt` is opened.

### Expected behavior

`a b.txt` should be opened instead.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PhyX-Meow** [comment]
Same issue here.
