### ISSUE TITLE
No Fedora 39 package built for Fedora 39 chroots (in COPR).

### ISSUE THREAD

**Issue by tetov** [wslutilities/wslu#298]
### Windows Version

Windows 10

### Windows Build Number

22621.2715

### WSL Version

WSL 2

### Distro Version

Fedora 39

### WSL Utilities Version

4.1.1

### Describe the bug

No build for Fedora 39 in COPR repo. I think you just need to trigger a rebuild for the fedora 39 chroot.

#### Doesn't work
```bash
dnf copr enable wslutilities/wslu
dnf install wslu -y
```

#### Cleanup

```bash
dnf copr remove wslutilities/wslu
```

#### Works

```bash
dnf install wslu --repofrompath 'wslu38,https://download.copr.fedorainfracloud.org/results/wslutilities/wslu/fedora-38-$basearch/' --setopt=wslu38.gpgkey=https://download.copr.fedorainfracloud.org/results/wslutilities/wslu/pubkey.gpg' -y
```

### Expected behavior

Package available for Fedora 39.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patrick330602** [comment]
The 4.1.2 release will include the support for Fedora 39-40.
