### ISSUE TITLE
PPA not available for Ubuntu 23.10 Mantic (and 24.04 Noble Numbat)

### ISSUE THREAD

**Issue by SunMar** [wslutilities/wslu#312]
### Windows Version

Windows 11

### Windows Build Number

23H2 (22631.3447)

### WSL Version

WSL 2

### Distro Version

Ubuntu 23.10 Mantic

### WSL Utilities Version

N/A

### Describe the bug

Running `sudo add-apt-repository ppa:wslutilities/wslu` produces the following error:

```Repository: 'Types: deb
URIs: https://ppa.launchpadcontent.net/wslutilities/wslu/ubuntu/
Suites: mantic
Components: main
'
Description:
Official repository for wslu packages
More info: https://launchpad.net/~wslutilities/+archive/ubuntu/wslu
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Hit:1 http://archive.ubuntu.com/ubuntu mantic InRelease
Hit:2 http://security.ubuntu.com/ubuntu mantic-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu mantic-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu mantic-backports InRelease
Ign:5 https://ppa.launchpadcontent.net/wslutilities/wslu/ubuntu mantic InRelease
Err:6 https://ppa.launchpadcontent.net/wslutilities/wslu/ubuntu mantic Release
  404  Not Found [IP: 185.125.190.80 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/wslutilities/wslu/ubuntu mantic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

### Steps to Reproduce

Try to install the PPA on Ubuntu 23.10 (and the just released 24.04 also doesn't appear to be available).
It does add a `/etc/apt/sources.list.d/wslutilities-ubuntu-wslu-mantic.sources` but there is no list file.

### Expected behavior

The PPA should be installed so I can install the latest version of wslu.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by catuhana** [comment]
In case someone comes here for a work-around, you can run `sudoedit /etc/apt/sources.list.d/wslutilities-ubuntu-wslu-noble.sources` and update the value of `Suites` line to `devel` or to the previous version's code name (in this case, `lunar`). This will give a warning when installing/updating package lists, though. And when this issue gets fixed, it would be better to remove the PPA with `add-apt-repository` and adding it back again.

**Comment by Stanzilla** [comment]
The newer releases are not available on launchpad anyway sadly

**Comment by trallnag** [comment]
I just clone the repo and install the scripts using make

**Comment by patrick330602** [comment]
<img width="1271" alt="Screenshot 2024-08-02 at 3 58 32 PM" src="https://github.com/user-attachments/assets/70794750-68b7-4a82-a561-6330254ff6a3">

The packages for wslu 4.1.3 is updated for Ubuntu 20.04, 22.04, 24.04 and 24.10. Although it is still on the release page, currently mantic is not allowing new packages.

**Comment by patrick330602** [comment]
Locally tested with Ubuntu 24.04 LTS arm64 version and works. Closing this ticket
