### ISSUE TITLE
Running `main_inst` from `configure.sh` will place executables at `/usr/usr/`

### ISSUE THREAD

**Issue by trallnag** [wslutilities/wslu#315]
### WSL Utilities Version

4.1.3

### Describe the bug

Running the function `main_inst` defined in `configure.sh` will place executables at `/usr/usr` because in the Makefile `PREFIX` defaults to `/usr` and the function sets `DESTDIR` to `/usr`.

- [X] I agree to follow this project's Code of Conduct

**Comment by patrick330602** [comment]
Thanks for reporting. This method is already deprecated long ago and it already no longer exists on the official installation methods here: https://wslutiliti.es/wslu/install.html and not documented in the contribution section: https://wslutiliti.es/wslu/contributing.html. I will remove the function to prevent further misunderstanding.
