### ISSUE TITLE
Different WSLInterop Name

### ISSUE THREAD

**Issue by SLKun** [wslutilities/wslu#319]
### Windows Version

Windows 11

### Windows Build Number

23H2 build 22635.3350

### WSL Version

WSL 2

### Distro Version

Debian 12

### WSL Utilities Version

4.1.3-1debian1

### Describe the bug

When run `wslview`, it propmt
```
$ wslview                                                                                
grep: /proc/sys/fs/binfmt_misc/WSLInterop: No such file or directory
[error] No input, aborting
```

### Steps to Reproduce

1. Just run `wslview`.

### Expected behavior

no error.

### Additional context

When I check the directorty `/proc/sys/fs/binfmt_misc/`, I find `WSLInterop-late` rather than `WSLInterop`
```bash
$ ls /proc/sys/fs/binfmt_misc/              
python3.11  register  status  WSLInterop-late
```

The content of `WSLInterop-late` is:
```bash
$ cat /proc/sys/fs/binfmt_misc/WSLInterop-late
enabled
interpreter /init
flags: P
offset 0
magic 4d5a
```

Kernel Version: `Linux SL-WJ16Pro 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 GNU/Linux`

`wsl.conf`:
```conf
[boot]
systemd=true
```

`.wslconfig`:
```conf
[wsl2]
memory=12GB
processors=6
localhostForwarding=false
guiApplications=true
nestedVirtualization=true
vmIdleTimeout=3600000
dhcp=true
firewall=false
dnsTunneling=false
autoProxy=false
swap=12884901888

[experimental]
autoMemoryReclaim=dropcache
sparseVhd=true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crramirez** [comment]
Please put your WSL version from `wsl --version`

**Comment by patrick330602** [comment]
After investigating, this seems to be generated by a systemd fix by Microsoft: https://github.com/microsoft/WSL/issues/8843

I will try to post a fix in the upcoming days.

**Comment by patrick330602** [comment]
wslu 4.1.4 is released; some packages should be already available.

**Comment by slycordinator** [comment]
> wslu 4.1.4 is released; some packages should be already available.

Where is this release?

1) The latest release here is 4.1.3.
2) And the latest (well, only) release on https://pkg.wslutiliti.es/debian is 4.1.3
Similarly, the Ubuntu PPA only goes up to version 4.1.3

**Comment by me-and** [comment]
@slycordinator it's not listed in GitHub releases, but it is available as a Git tag: https://github.com/wslutilities/wslu/releases/tag/v4.1.4

It normally takes a while for upstream releases to make it into distribution package managers, which is entirely up to each distribution to manage.
