### ISSUE TITLE
Was support for OpenSUSE Tumbleweed dropped?

### ISSUE THREAD

**Issue by julienavert** [wslutilities/wslu#321]
Hello and thank you for your work.

In the past, I followed the instructions from this documentation https://wslutiliti.es/wslu/install.html#tumbleweed and successfully installed the repo and `wslu` on my tumbleweed WSL2.

Today, I tried to refresh `zypper` repositories and update my packages, but the `wslu` repo does not exist anymore.

Looking at this page https://copr.fedorainfracloud.org/coprs/wslutilities/wslu/ it looks like tumbleweed is not offered anymore as a release target ? It also looks like OpenSUSE Leap 15.4 is being deleted (EOL) in about 4 months.

Was support for OpenSUSE, and particularly tumbleweed, dropped?

Thank you.

**Comment by patrick330602** [comment]
OpenSUSE Tumbleweed support is recovered.
