### ISSUE TITLE
Network traffic not forwarded from Windows browser to WSL2 distro

### ISSUE THREAD

**Issue by garysassano** [wslutilities/wslu#322]
### Windows Version

Windows 10

### Windows Build Number

W10 21H2

### WSL Version

WSL 2

### Distro Version

Ubuntu 24.04

### WSL Utilities Version

4.1.3

### Describe the bug

After running `aws configure sso`, the default Windows browser opens via `wslview`. However, after completing the authentication in the browser, the localhost response doesn't reach the WSL2 machine.

### Steps to Reproduce

Set `export BROWSER=/usr/bin/wslview` in your `.bashrc` file.

Run `aws configure sso` in your bash terminal.

### Expected behavior

I expected the localhost response would reach the WSL2 machine.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patrick330602** [comment]
wslview relies on powershell.exe/cmd.exe to open the website. this would be a better fit to be a feature request for in upstream WSL repo: https://github.com/microsoft/WSL
