### ISSUE TITLE
Opening default windows browser in VSCode does not work

### ISSUE THREAD

**Issue by AceHack** [wslutilities/wslu#39]
WinVer: 1809 - 17763.107
WLinux Latest

See issue https://github.com/WhitewaterFoundry/WLinux/issues/180

When you go to sign into Azure it has a button that says Copy and Open.  This button works on windows and opens the default browser, in WSL it does not.

![azuresignin](https://user-images.githubusercontent.com/578953/48424988-deab9280-e731-11e8-9d5f-eb815c9fced1.jpg)

**Comment by patrick330602** [comment]
thank you for the report. I will look into this.
