### ISSUE TITLE
Doesn't follow root mount directory set in wsl.conf

### ISSUE THREAD

**Issue by jordandrako** [wslutilities/wslu#40]
**Background Information:**
 - Build: 17763.55
 - WSL: WLinux Debian GNU/Linux 9 (stretch)
 - Version: 1.9.25

**Describe the bug**
In /etc/wsl.conf, I have `root = /` set so instead of my drives being in `/mnt/c /mnt/d` etc, they are at `/c /d`. These utilities only look in /mnt so many of them error out with "No such file or directory".

**To Reproduce**
1. `sudo nano /etc/wsl.conf`
1. Add/change under `[automount]` the root option to `root = /`
1. Restart anything related to wsl so the drives can be remounted.
1. See if it worked by running `ls -la /` to see if `c` is listed.
1. Run `wslusc` or other command to see the errors.

**Expected behavior**
If drives are mounted elsewhere than "mnt", the scripts should find the right drive.

**Additional context**

**Comment by cicorias** [comment]
something like this might be useful
```
awk -F "=" '/root/ {print $2}' /etc/wsl.conf
```
If nothing comes back, then it's default of `/mnt/...`   - otherwise, it's the requested mount path.

In wsl.conf - it comes back as `/` if 

`root=/`

**Comment by patrick330602** [comment]
@ thank you! I will do the implementation very soon, I am a bit busy recently with my schoolwork, so the process implementing them will be a bit slow. I will set this as priority.

**Comment by patrick330602** [comment]
This issue is fixed in develop branch, will release once the manpage is completed

**Comment by khuongduybui** [comment]
How did you fix this?
I have found that using `wslpath` directly is more accurate / convenient than figuring out mount point from `/etc/wsl.conf`, which might be changed but not taken into effect yet (hasn't restarted).
