### ISSUE TITLE
wslview -r not setting default browser

### ISSUE THREAD

**Issue by ezhikov** [wslutilities/wslu#44]
**Background Information:**
 - Build: 17763
 - WSL: Wlinux
 - Version: v1.9.02

**Describe the bug**
Looks like `wslview -r` does nothing, or it's not clear how to proceed

**To Reproduce**
`wslview -r`

**Expected behavior**
should set default browser, so links will open in default windows browser

**Additional context**
Got this message:
```
update-alternatives: --install needs <link> <name> <path> <priority>

Use 'update-alternatives --help' for program usage information.
update-alternatives: --install needs <link> <name> <path> <priority>
```

**Comment by patrick330602** [comment]
Thank you for your feedback. This bug is fixed in development branch. For temporary fix, you can execute following in your terminal:
```
sudo update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/bin/wslview 1
sudo update-alternatives --install /usr/bin/www-browser www-browser /usr/bin/wslview 1
```
