### ISSUE TITLE
Please clarify the license of wsl.ico

### ISSUE THREAD

**Issue by rbalint** [wslutilities/wslu#57]
https://github.com/wslutilities/wslu/blob/master/src/etc/wsl.ico does not seem to be original work and it is not clear what the license of it and if it is redistributable at  all.

Please either clarify the license or replace it in the repository to clear the legal status of the project.

**Comment by patrick330602** [comment]
Thank you for reminding me. Will remove icon when I am trying to confirm its license.

**Comment by patrick330602** [comment]
Thank you for feedback. After some research, original artwork author cannot be contacted anymore. I will switch to [this tux logo](https://github.com/garrett/Tux) as it is in public domain. Credit will be added to master branch after 2.0.0 release as well as Wiki.
