### ISSUE TITLE
wslusc: Please detect which wsl distribution should be used to start the command

### ISSUE THREAD

**Issue by rbalint** [wslutilities/wslu#58]
**Background Information:**
 - Build: all
 - WSL: Ubuntu 16.04 and Ubuntu 18.04
 - Version: 1.9

**Describe the bug**
When wslusc is executed it creates a link to start the specified command in the _default_ WSL distribution.

**To Reproduce**
* Install both Ubuntu 16.04 and Ubuntu 18.04 WSL apps.
* Install xterm in the non-default one
* Run ```wslusc -g xterm``` in the non-default one
* Observe that the created shortcut tries to start xterm in the default distribution, failing to do so.

**Expected behavior**
Wslusc should detect which WSL distribution name should the shortcut use to start the command in the right distribution.

**Comment by patrick330602** [comment]
Thank you for the feedback. I will look into this issue.

**Comment by patrick330602** [comment]
This problem is now fixed in the develop branch. it will now respect its current WSL distribution.
