### ISSUE TITLE
[New Feature] wslstart

### ISSUE THREAD

**Issue by ghost** [wslutilities/wslu#64]
the Cygwin project has this tool, which opens a FILE with the default application

it seems the closest match is wslview, but only works with URLs not local files

**Comment by cup** [comment]
https://github.com/msys2/MSYS2-packages/issues/754

**Comment by crramirez** [comment]
Hello,

wslview works with local files that are outside the Linux home:

```
cd /mnt/c/Users/xxxx/Documents
wslview anydocument.docx

```
With Windows 19.03 we expect that files in the Linux home folder can be opened as well.

Regards

**Comment by patrick330602** [comment]
Thank you for the feedback. Like @crramirez have mentioned, wslview can work with other formats, it is just registered as default browser in WSL. I will give a alternative name for wslview and update documentation so that people will not misunderstand the usage of `wslview`.
