### ISSUE TITLE
why is wslupath deprecated

### ISSUE THREAD

**Issue by cup** [wslutilities/wslu#65]
it seems the tool is still useful

users wont always need to just convert environmental variables

users might need to convert arbitrary paths

Cygwin project has similar tool Cygpath

**Comment by patrick330602** [comment]
WSL now have a better wsl path conversion tool `wslpath` provided by Microsoft that is builtin for all distros. `wslupath` is still here for compatibility.

**Comment by roachsinai** [comment]
So is this the reason why wslupath not works for me in below situation:

```
owin ~ » wslupath '/tmp/vimge_paste5152'
[error] No proper path form detected: /tmp/vimge_paste5152.
```

**Comment by patrick330602** [comment]
> So is this the reason why wslupath not works for me in below situation:
> 
> ```
> owin ~ » wslupath '/tmp/vimge_paste5152'
> [error] No proper path form detected: /tmp/vimge_paste5152.
> ```

Yep, it is suggested to no longer use it but use the builtin `wslpath` instead

**Comment by roachsinai** [comment]
> > So is this the reason why wslupath not works for me in below situation:
> > ```
> > owin ~ » wslupath '/tmp/vimge_paste5152'
> > [error] No proper path form detected: /tmp/vimge_paste5152.
> > ```
> 
> Yep, it is suggested to no longer use it but use the builtin `wslpath` instead

Got it, thanks for reply!
