### ISSUE TITLE
x-www-browser - tcgetpgrp problem.

### ISSUE THREAD

**Issue by thunderbirdtr** [wslutilities/wslu#66]
**Background Information:**
 - Build: 18875.1000 (version 1903)
 - WSL:  Pengwin
 - Version: 1.2.3.0

**Describe the bug**
x-www-browser command has problem with "tcgetpgrp" and It looks like "tcgetpgrp" problem. But when I checked the internet it shows, it is an old bug and It was fixed.
 

**To Reproduce**
I ran jupyter lab (it should open "localhost" link for auth) 

**Expected behavior**
x-www-browser should work

**Additional context**

To confirm it is actually coming from your x-www-browser 

<img width="1039" alt="bug1" src="https://user-images.githubusercontent.com/1688848/56502706-f591b480-651b-11e9-9fdc-9f1d39bd3c69.PNG">

First picture with "windows interoperability"

<img width="912" alt="bug2" src="https://user-images.githubusercontent.com/1688848/56502750-10fcbf80-651c-11e9-8745-26b908b7a449.PNG">

Second picture has no "windows interoperability" and basically no "tcgetpgrp" problem appeared 

If there is anything needed, I would love to provide it.

Thank you.

**Comment by patrick330602** [comment]
Thanks for the feedback. I already know which part is causing the problem with your screenshot, but this is a tricky issue, which will possibly take some time to fix it. You might want to unregister `wslview` as the default browser using `wslview -u` for now.

**Comment by swebs** [comment]
Just wanted to add a bit more info here, though perhaps this is already fixed. When I have `wslview` registered and I run
`xdg-open filename.html`
I get the following:
```
Start : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:1
+ Start "/home/swebs/cwfp/bokeh-grid.html"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```
without the `tcgetpgrp` message (though I have seen that as well when trying to open URLs in slightly different ways). When `wslview` is unregistered the `xdg-open` command fails as I have no alternative browser installed. This is on `pengwin`.

**Comment by patrick330602** [comment]
@swebs Thank you for the information provided. I will take a further look at whether the fix works for this.
