### ISSUE TITLE
Quick fix for wslview failing when URL includes &(ampersand)

### ISSUE THREAD

**Issue by kazuau** [wslutilities/wslu#68]
**Background Information:**
 - Build: 1809 (OS Build: 17763.437)
 - WSL: Pengwin 1.2.3.0
 - Version: wslu v2.1.1; wslview v06

**Describe the bug**
When '&' character is included in the target URL, the command fails with following apparent powershell error message:
`The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.`

**To Reproduce**
From login bash shell:
`wslview 'http://www.google.com/search?q=wslu&hl=en'`

**Expected behavior**
The destination URL opens in the Windows default web browser..

**Additional context**
Above issue in my environment is corrected by following quick fix:
```
*** wslview.old 2019-04-12 09:00:58.000000000 +0900
--- wslview.new 2019-04-25 22:32:54.237179800 +0900
***************
*** 154,160 ****
  done

  if [[ "$lname" != "" ]]; then
!       winps_exec Start "$lname"
  else
        echo "${error}No input, aborting"
        exit 21
--- 154,160 ----
  done

  if [[ "$lname" != "" ]]; then
!       winps_exec Start "\"$lname\""
  else
        echo "${error}No input, aborting"
        exit 21
```

**Comment by patrick330602** [comment]
Thank you very much for finding and fixing the bug! will fix it right now.
