### ISSUE TITLE
wslu complete re-written in C (which will be lib actually)

### ISSUE THREAD

**Issue by patrick330602** [wslutilities/wslu#72]

**Comment by crramirez** [comment]
Well my first question is what is the advantage? A better speed is needed for wslu? Or not be able to modify it without compiling?

**Comment by patrick330602** [comment]
Well, this is mostly a proposal for now... The reason is that the new component of wslu `wslconf` is written in C, so I want to keep it consistent. Also, I might try to write a C lib for wslu (like `wslpy`, the python library of wslu). This might end up in a new repo for people who wants it.

**Comment by patrick330602** [comment]
After some thoughts, wslu in c will still be on the todo list, but it won't come to main branch of wslu.
