### ISSUE TITLE
convert-im6.q16: width or height exceeds limit `/c/Users/axhe/wslu/designer-qt5.ico' @ error/icon.c/WriteICONImage/928.

### ISSUE THREAD

**Issue by axhe** [wslutilities/wslu#76]
**Background Information:**
 - WSL: [Ubuntu 18.04]
`sudo dpkg -l | grep wslu
ii  wslu                                       2.2.0-0                             all          A collection of utilities for Windows 10 Linux Subsystem`

**Describe the bug**
Creating the ico file fails error.

Command:
`wslusc --name Qt 5 Designer --icon /usr/share/pixmaps/designer-qt5.png --gui /usr/lib/qt5/bin/designer`
Output:
```
[info] You choose to use custom icon: /usr/share/pixmaps/designer-qt5.png. Processing...
[info] Converting png icon to ico...
convert-im6.q16: width or height exceeds limit `/c/Users/axhe/wslu/designer-qt5.ico' @ error/icon.c/WriteICONImage/928.
[info] the following custom variable/command will be applied: source ~/.wslenv;
[info] Create shortcut Qt 5 Designer.lnk successful
```

**To Reproduce**
install qtcreator in Ubuntu 18.04 and create the link as in above command.

**Workaround/fix**
Setting `-resize 256X256` for the convert command in wslusc fixes the issue for me.

**Comment by patrick330602** [comment]
Sorry for the inconvenience caused. This bug will be fixed very soon.

**Comment by patrick330602** [comment]
wslu 2.2.1 is released to resolve this problem. The update will be coming very soon.

**Comment by axhe** [comment]
Thanks!
