### ISSUE TITLE
Space around = in /etc/wsl.conf is not recocognized correctly

### ISSUE THREAD

**Issue by axhe** [wslutilities/wslu#78]
**Background Information:**
 - WSL: [Ubuntu 18.04]
 - Version: [wslu 2.2.0-0]

**Describe the bug**
In /etc/wsl.conf spaces around the = do not work.
This entry in wsl.conf is not recognized correctly:
`root = /`

This one works:
`root=/`

**Comment by patrick330602** [comment]
I have tested but it works. Can you post the content in your `/etc/wsl.conf`?

**Comment by axhe** [comment]
Unfortunately i cannot reproduce it now either. Possibly some "wrong" character got into when i copied the wsl.conf from a blog article.

Thanks for your effort.
