### ISSUE TITLE
No release file on Disco

### ISSUE THREAD

**Issue by VArterJr** [wslutilities/wslu#80]
**Background Information:**
 - Build: 18362.175
 - WSL: Ubuntu 19.04
 - Version: 2.1 (Latest?)

**Describe the bug**
When installed on Ubuntu 19.04, I can no longer do apt (apt-get) update. It fails with:
```
Hit:1 http://archive.ubuntu.com/ubuntu disco InRelease
Get:2 http://archive.ubuntu.com/ubuntu disco-updates InRelease [97.5 kB]
Get:3 http://archive.ubuntu.com/ubuntu disco-backports InRelease [88.8 kB]
Get:4 http://security.ubuntu.com/ubuntu disco-security InRelease [97.5 kB]
Ign:5 https://packagecloud.io/whitewaterfoundry/wslu/ubuntu disco InRelease
Err:6 https://packagecloud.io/whitewaterfoundry/wslu/ubuntu disco Release
  404  Not Found [IP: 54.241.144.200 443]
Reading package lists... Done
E: The repository 'https://packagecloud.io/whitewaterfoundry/wslu/ubuntu disco Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**To Reproduce**
* Install Ubuntu from Windows Store.
* Change channel to "normal"
* Release upgrade to 19.04
* Install wslu per instructions
* Try to do sudo apt upgrade (or sudo apt-get upgrade)

**Expected behavior**
I would expect apt not to fail. I see there is no Disco release file, but everything installed correctly, just can't update anything anymore.

**Comment by patrick330602** [comment]
Thank you for your report! Unfortunately, Ubuntu Disco is not a [supported distro](https://github.com/wslutilities/wslu/wiki#currently-supported-distro). Alternatively, manually change the distro name in your apt source list from `disco` to `bionic`. Hope this help you.
