### ISSUE TITLE
Unsupported OS???

### ISSUE THREAD

**Issue by rootorben** [wslutilities/wslu#81]
WTF? 

uname -a
Linux PC 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 GNU/Linux`

me@pc:~$ curl -s https://packagecloud.io/install/repositories/whitewaterfoundry/wslu/script.deb.sh | sudo bash
[sudo] password for me:
Detected operating system as Kali/kali-rolling.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/whitewaterfoundry_wslu.list...curl: (22) The requested URL returned error: 404

Unable to download repo config from: https://packagecloud.io/install/repositories/whitewaterfoundry/wslu/config_file.list?os=Kali&dist=kali-rolling&source=script

This usually happens if your operating system is not supported by
packagecloud.io, or this script's OS detection failed.

You can override the OS detection by setting os= and dist= prior to running this script.
You can find a list of supported OSes and distributions on our website: https://packagecloud.io/docs#os_distro_version

For example, to force Ubuntu Trusty: os=ubuntu dist=trusty ./script.sh

If you are running a supported OS, please email support@packagecloud.io and report this.`

**Comment by patrick330602** [comment]
Sorry for the inconvenience caused. packagecloud.io doesn't support Kali Linux, although we have sent multiple requests to the team to add Kali support. for now, you have to install deb package using the one on the release page.
