### ISSUE TITLE
wslusc screws fonts

### ISSUE THREAD

**Issue by seb128** [wslutilities/wslu#83]
Using W10 r18932

Typing 'wslusc' on a WSL2/Ubuntu 18.04 uptodate instance leads to have the Ubuntu instance font changing/being screwed untill the app is restarted

**Comment by patrick330602** [comment]
Hi,

Can you post your version of your wslu? you can check by `wslusc --version`. thank you!

**Comment by seb128** [comment]
wslu v2.0.0: wlusc v20 (which is installed by default on the Ubuntu 18 image)

**Comment by rbalint** [comment]
reproducible with current wslu master with the following steps:
```
bash ./configure.sh
make
PATH=$PATH:./out out/wslusc --help
```

**Comment by gdoenlen** [comment]
This happens with wslsys as well. The window gets smaller and fonts bolder.

```sh
 ~> wslsys --version
wslu v2.0.0; wslsys v28
```

**Comment by patrick330602** [comment]
Thank you for all of your feedback. This is mostly related to the `conhost.exe` behavior, I still need some time trying to figure out the proper way to handle this behavior properly.

**Comment by shanselman** [comment]
What is WSLU doing that would upset conhost.exe? Poking around in the registry? Let me know and I'll route this to the right people.

**Comment by crramirez** [comment]
Just calling powershell. This is a known issue when you invoke powershell from WSL

**Comment by patrick330602** [comment]
@shanselman This is mostly suspected to be the problem of the `powerhshell.exe` as @crramirez mentioned. When executing `powershell.exe` in wslu, the settings from the console window for PowerShell will be brought to the current window, so I kind of suspecting this is in some level related to `conhost`.

**Comment by shanselman** [comment]
@craigaloewen @DHowett-MSFT @miniksa is this known? Folks here are saying this is a known messy thing but this is the first I've heard of it. Version specific? Display specific?

**Comment by DHowett-MSFT** [comment]
Powershell sets and resets the system codepage, which it shouldn't be doing. This can cause the fonts to reset to "raster fonts". This isn't something conhost can fix, as it will break compatibility with applications that need the codepage and font to match.

**Comment by patrick330602** [comment]
Just figure out a dirty way to fix this problem(but it works, kind of), will be on next release
![image](https://user-images.githubusercontent.com/15316889/62003750-39650d00-b14e-11e9-8f75-0834d02378cd.png)

**Comment by patrick330602** [comment]
the latest develop branch fixed this problem (at least on my computer and my Virtual Machine). Further testing is needed.
