### ISSUE TITLE
Performance issue due to usage of Powershell

### ISSUE THREAD

**Issue by paulstelian97** [wslutilities/wslu#84]
**Background Information:**
 - Build: 18362 (19h1_release)
 - WSL: Ubuntu 18.04.2 LTS (Ubuntu in Store)
 - Version: wslu 2.0.0, wslfetch v38

**Describe the bug**
wslfetch takes a long time to display output (I've seen it vary between 7 and 15 seconds). wslsys takes 1.5-3 seconds itself.

**To Reproduce**
Steps to reproduce the behavior: Just run wslfetch with no parameters (same for wslsys)

**Expected behavior**
The output should appear more quickly.

**Additional context**
I initially suspected that it was Powershell being slow but I can't seem to get it to show in my task manager so I may be wrong. You don't call it THAT many times do you?

I will also investigate on a solution myself.

**Comment by paulstelian97** [comment]
I've put in some prints between the lines in wslsys and apparently the lines that run Powershell take a full half-second to run. I will try to devise ways to call cmd.exe instead (and `reg query` commands) to make it faster. If I succeed, I'll bring up a pull request.

**Comment by patrick330602** [comment]
I believe this is the existing problem for `wslfetch`, as it doesn't cache information as `neofetch` or `screenfetch`. the performance using `powershell.exe` and `reg.exe` is actually pretty similar.

**Comment by paulstelian97** [comment]
So it means that it's something specific to my system that the performance with powershell.exe is much worse? Considering the same number of calls to a Windows executable (either powershell or reg) from my patch it definitely makes a difference on my system. Does it not on yours?

**Comment by patrick330602** [comment]
Interesting. I will do another test on virtual machine just for that. I don't want to get into "It works on my machine" situation.

**Comment by paulstelian97** [comment]
Do try to limit CPU performance (my old laptop had i3-5005u and it took even more than that half-second for Powershell to launch, my current personal laptop has an i5-8250u and still takes that half-second to launch, my work laptop has some i7 [HQ category] and Powershell starts before the window launch animation ends).

**Comment by patrick330602** [comment]
You are right, on a computer that is not that powerful, the two commands showed a huge speed difference. there's still a little bit things to modify in your PR
