### ISSUE TITLE
Wslu cannot handle windows user names containing spaces

### ISSUE THREAD

**Issue by iernstig** [wslutilities/wslu#89]
**Background Information:**
 - Build: [e.g. 18362]
 - WSL: [Arch Linux 4.4.0-18362-Microsoft]
 - Version: [ - ]

**Describe the bug**
When trying to use utilities in the library (which I installed from AUR) the space in my windows user name causes the functionality to break in both wslfetch.sh and wslusc.sh (might be more but these two I tested)
**To Reproduce**
Have username which contains a white space character on windows where you installed

**Comment by iernstig** [comment]
[warn] Default wslusc icon "wsl.ico" not found in Windows directory. Copying right now...
[info] Default wslusc icon "wsl.ico" copied. Located at /mnt/c/Users/Amerden Intern/wslu.
[warn] runHidden.vbs not found in Windows directory. Copying right now...
[info] runHidden.vbs copied. Located at /mnt/c/Users/Amerden Intern/wslu.
At line:1 char:563
+ ... instead of '\\' EX: wslpath 'c:\\users' run "cd ~; export DISPLAY=:0; ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token '\\' EX: wslpath 'c:\\users' run "cd ~; export DISPLAY=:0;  emacs"'' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

mv: cannot stat '/mnt/c/Users/AMERDE~1/AppData/Local/Temp/emacs.lnk': No such file or directory
[info] Create shortcut emacs.lnk successful

**Comment by patrick330602** [comment]
Thank you for your bug report. I will fix the issue as soon as possible, sorry for the inconvenience caused.

**Comment by iernstig** [comment]
@patrick330602 No worries! Just glad to have the utils 😃

**Comment by patrick330602** [comment]
@iernstig Some more information is needed. Can you show me the output of `wslfetch --debug`?

**Comment by paulstelian97** [comment]
Noticed you passed "cd ~" to Powershell. I don't think Powershell knows that and since that "~" is between quotes it is not expanded by Bash to some Linux path either. (not that that would be useful).

I think you may wish to use the $HOME variable in there. You figure the quoting or, if I get enough free time, I may try to look into it myself.

**Comment by patrick330602** [comment]
Sorry for the late reply. I have tried several testing but I am really unable to reproduce this bug. 
The `cd ~` here is used for WSL side to keep Linux executable to be execute under Linux directory instead of Windows Directory to prevent problem.

**Comment by patrick330602** [comment]
Okay never mind, I think I accidentally fix this bug when checking the code with codefactor....
